// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: admin.proto

package sitepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PromptText carries the single QOTD generation instruction.
type PromptText struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromptText) Reset() {
	*x = PromptText{}
	mi := &file_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptText) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptText) ProtoMessage() {}

func (x *PromptText) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptText.ProtoReflect.Descriptor instead.
func (*PromptText) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{0}
}

func (x *PromptText) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// PostPreview is the result of a dry-run: the generated post body, a title, the rendered RSS feed
// XML, and an error string (set when generation failed, e.g. no OpenAI key).
type PostPreview struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          string                 `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Rss           string                 `protobuf:"bytes,3,opt,name=rss,proto3" json:"rss,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	News          string                 `protobuf:"bytes,5,opt,name=news,proto3" json:"news,omitempty"` // the headline the prompt was generated against (context)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostPreview) Reset() {
	*x = PostPreview{}
	mi := &file_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostPreview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostPreview) ProtoMessage() {}

func (x *PostPreview) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostPreview.ProtoReflect.Descriptor instead.
func (*PostPreview) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{1}
}

func (x *PostPreview) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *PostPreview) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PostPreview) GetRss() string {
	if x != nil {
		return x.Rss
	}
	return ""
}

func (x *PostPreview) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *PostPreview) GetNews() string {
	if x != nil {
		return x.News
	}
	return ""
}

// SlackConfig is the Slack posting configuration. On read, webhook_url is empty and webhook_set
// reports whether one is stored; on write, a blank webhook_url leaves the stored value unchanged.
type SlackConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WebhookUrl    string                 `protobuf:"bytes,1,opt,name=webhook_url,json=webhookUrl,proto3" json:"webhook_url,omitempty"`
	Enabled       bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"` // when true, the server auto-posts the daily discussion (scheduled posting)
	WebhookSet    bool                   `protobuf:"varint,3,opt,name=webhook_set,json=webhookSet,proto3" json:"webhook_set,omitempty"`
	PostHour      int32                  `protobuf:"varint,4,opt,name=post_hour,json=postHour,proto3" json:"post_hour,omitempty"` // hour of day (0–23, server local time) the scheduled daily post fires
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlackConfig) Reset() {
	*x = SlackConfig{}
	mi := &file_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlackConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlackConfig) ProtoMessage() {}

func (x *SlackConfig) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlackConfig.ProtoReflect.Descriptor instead.
func (*SlackConfig) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{2}
}

func (x *SlackConfig) GetWebhookUrl() string {
	if x != nil {
		return x.WebhookUrl
	}
	return ""
}

func (x *SlackConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *SlackConfig) GetWebhookSet() bool {
	if x != nil {
		return x.WebhookSet
	}
	return false
}

func (x *SlackConfig) GetPostHour() int32 {
	if x != nil {
		return x.PostHour
	}
	return 0
}

// TailoringId identifies a saved variant.
type TailoringId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TailoringId) Reset() {
	*x = TailoringId{}
	mi := &file_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TailoringId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TailoringId) ProtoMessage() {}

func (x *TailoringId) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TailoringId.ProtoReflect.Descriptor instead.
func (*TailoringId) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{3}
}

func (x *TailoringId) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// TailoringMeta is the glanceable summary of a saved variant (no résumé payload).
type TailoringMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	JobUrl        string                 `protobuf:"bytes,2,opt,name=job_url,json=jobUrl,proto3" json:"job_url,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Company       string                 `protobuf:"bytes,4,opt,name=company,proto3" json:"company,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // unix seconds
	Keywords      []string               `protobuf:"bytes,6,rep,name=keywords,proto3" json:"keywords,omitempty"`                     // top job keywords — what the tailoring emphasized, at a glance
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TailoringMeta) Reset() {
	*x = TailoringMeta{}
	mi := &file_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TailoringMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TailoringMeta) ProtoMessage() {}

func (x *TailoringMeta) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TailoringMeta.ProtoReflect.Descriptor instead.
func (*TailoringMeta) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{4}
}

func (x *TailoringMeta) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TailoringMeta) GetJobUrl() string {
	if x != nil {
		return x.JobUrl
	}
	return ""
}

func (x *TailoringMeta) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TailoringMeta) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *TailoringMeta) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *TailoringMeta) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

// TailoringList is the saved variants, newest first.
type TailoringList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*TailoringMeta       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TailoringList) Reset() {
	*x = TailoringList{}
	mi := &file_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TailoringList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TailoringList) ProtoMessage() {}

func (x *TailoringList) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TailoringList.ProtoReflect.Descriptor instead.
func (*TailoringList) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{5}
}

func (x *TailoringList) GetItems() []*TailoringMeta {
	if x != nil {
		return x.Items
	}
	return nil
}

// Settings is the web-editable configuration. On GetSettings the key is never populated (only
// key_set); on SaveSettings a non-empty openai_api_key is stored and a blank one is ignored.
type Settings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OpenaiApiKey  string                 `protobuf:"bytes,1,opt,name=openai_api_key,json=openaiApiKey,proto3" json:"openai_api_key,omitempty"`
	OpenaiModel   string                 `protobuf:"bytes,2,opt,name=openai_model,json=openaiModel,proto3" json:"openai_model,omitempty"`
	KeySet        bool                   `protobuf:"varint,3,opt,name=key_set,json=keySet,proto3" json:"key_set,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Settings) Reset() {
	*x = Settings{}
	mi := &file_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Settings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Settings) ProtoMessage() {}

func (x *Settings) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Settings.ProtoReflect.Descriptor instead.
func (*Settings) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{6}
}

func (x *Settings) GetOpenaiApiKey() string {
	if x != nil {
		return x.OpenaiApiKey
	}
	return ""
}

func (x *Settings) GetOpenaiModel() string {
	if x != nil {
		return x.OpenaiModel
	}
	return ""
}

func (x *Settings) GetKeySet() bool {
	if x != nil {
		return x.KeySet
	}
	return false
}

// ModelList is the set of selectable model ids.
type ModelList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []string               `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelList) Reset() {
	*x = ModelList{}
	mi := &file_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelList) ProtoMessage() {}

func (x *ModelList) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelList.ProtoReflect.Descriptor instead.
func (*ModelList) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{7}
}

func (x *ModelList) GetModels() []string {
	if x != nil {
		return x.Models
	}
	return nil
}

// Empty is a no-argument request.
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{8}
}

// LoginRequest carries the admin username + password.
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{9}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// LoginReply returns a signed JWT on success.
type LoginReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReply) Reset() {
	*x = LoginReply{}
	mi := &file_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReply) ProtoMessage() {}

func (x *LoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReply.ProtoReflect.Descriptor instead.
func (*LoginReply) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{10}
}

func (x *LoginReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *LoginReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// AuthStateReply tells the client which auth screen to show.
type AuthStateReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NeedsSetup    bool                   `protobuf:"varint,1,opt,name=needs_setup,json=needsSetup,proto3" json:"needs_setup,omitempty"`      // true on a fresh, unconfigured deploy — show the setup screen
	RecoveryHint  string                 `protobuf:"bytes,2,opt,name=recovery_hint,json=recoveryHint,proto3" json:"recovery_hint,omitempty"` // owner-chosen memory jog for the reset screen ("" if no account/hint)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthStateReply) Reset() {
	*x = AuthStateReply{}
	mi := &file_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthStateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthStateReply) ProtoMessage() {}

func (x *AuthStateReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthStateReply.ProtoReflect.Descriptor instead.
func (*AuthStateReply) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{11}
}

func (x *AuthStateReply) GetNeedsSetup() bool {
	if x != nil {
		return x.NeedsSetup
	}
	return false
}

func (x *AuthStateReply) GetRecoveryHint() string {
	if x != nil {
		return x.RecoveryHint
	}
	return ""
}

// SetupRequest creates the first owner account. setup_token is required only when the server has
// ADMIN_SETUP_TOKEN configured.
type SetupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Hint          string                 `protobuf:"bytes,3,opt,name=hint,proto3" json:"hint,omitempty"`
	SetupToken    string                 `protobuf:"bytes,4,opt,name=setup_token,json=setupToken,proto3" json:"setup_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetupRequest) Reset() {
	*x = SetupRequest{}
	mi := &file_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupRequest) ProtoMessage() {}

func (x *SetupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupRequest.ProtoReflect.Descriptor instead.
func (*SetupRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{12}
}

func (x *SetupRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SetupRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *SetupRequest) GetHint() string {
	if x != nil {
		return x.Hint
	}
	return ""
}

func (x *SetupRequest) GetSetupToken() string {
	if x != nil {
		return x.SetupToken
	}
	return ""
}

// SetupReply returns a session token and the one-time recovery phrase (shown once). On failure ok is
// false and error carries a human-readable reason.
type SetupReply struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Ok             bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Token          string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	RecoveryPhrase string                 `protobuf:"bytes,3,opt,name=recovery_phrase,json=recoveryPhrase,proto3" json:"recovery_phrase,omitempty"`
	Error          string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SetupReply) Reset() {
	*x = SetupReply{}
	mi := &file_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupReply) ProtoMessage() {}

func (x *SetupReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupReply.ProtoReflect.Descriptor instead.
func (*SetupReply) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{13}
}

func (x *SetupReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SetupReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *SetupReply) GetRecoveryPhrase() string {
	if x != nil {
		return x.RecoveryPhrase
	}
	return ""
}

func (x *SetupReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ResetRequest resets the owner password using the recovery phrase (or the env break-glass token).
type ResetRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RecoveryPhrase string                 `protobuf:"bytes,1,opt,name=recovery_phrase,json=recoveryPhrase,proto3" json:"recovery_phrase,omitempty"`
	NewPassword    string                 `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResetRequest) Reset() {
	*x = ResetRequest{}
	mi := &file_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetRequest) ProtoMessage() {}

func (x *ResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetRequest.ProtoReflect.Descriptor instead.
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{14}
}

func (x *ResetRequest) GetRecoveryPhrase() string {
	if x != nil {
		return x.RecoveryPhrase
	}
	return ""
}

func (x *ResetRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

// ResetReply returns the rotated recovery phrase (shown once) on success; error on failure.
type ResetReply struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Ok             bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	RecoveryPhrase string                 `protobuf:"bytes,2,opt,name=recovery_phrase,json=recoveryPhrase,proto3" json:"recovery_phrase,omitempty"`
	Error          string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResetReply) Reset() {
	*x = ResetReply{}
	mi := &file_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetReply) ProtoMessage() {}

func (x *ResetReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetReply.ProtoReflect.Descriptor instead.
func (*ResetReply) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{15}
}

func (x *ResetReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ResetReply) GetRecoveryPhrase() string {
	if x != nil {
		return x.RecoveryPhrase
	}
	return ""
}

func (x *ResetReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// SearchRequest is an AniList search query.
type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{16}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

// AnimeId identifies one show by its AniList id.
type AnimeId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AnilistId     int32                  `protobuf:"varint,1,opt,name=anilist_id,json=anilistId,proto3" json:"anilist_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnimeId) Reset() {
	*x = AnimeId{}
	mi := &file_admin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnimeId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnimeId) ProtoMessage() {}

func (x *AnimeId) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnimeId.ProtoReflect.Descriptor instead.
func (*AnimeId) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{17}
}

func (x *AnimeId) GetAnilistId() int32 {
	if x != nil {
		return x.AnilistId
	}
	return 0
}

// CheckReply reports how many tracked shows changed during a release check.
type CheckReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Updated       int32                  `protobuf:"varint,1,opt,name=updated,proto3" json:"updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckReply) Reset() {
	*x = CheckReply{}
	mi := &file_admin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckReply) ProtoMessage() {}

func (x *CheckReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckReply.ProtoReflect.Descriptor instead.
func (*CheckReply) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{18}
}

func (x *CheckReply) GetUpdated() int32 {
	if x != nil {
		return x.Updated
	}
	return 0
}

// Anime is one show — an AniList search result or a tracked entry.
type Anime struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AnilistId     int32                  `protobuf:"varint,1,opt,name=anilist_id,json=anilistId,proto3" json:"anilist_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Format        string                 `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Episodes      int32                  `protobuf:"varint,5,opt,name=episodes,proto3" json:"episodes,omitempty"`
	SeasonYear    int32                  `protobuf:"varint,6,opt,name=season_year,json=seasonYear,proto3" json:"season_year,omitempty"`
	CoverImage    string                 `protobuf:"bytes,7,opt,name=cover_image,json=coverImage,proto3" json:"cover_image,omitempty"`
	Tracked       bool                   `protobuf:"varint,8,opt,name=tracked,proto3" json:"tracked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Anime) Reset() {
	*x = Anime{}
	mi := &file_admin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Anime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Anime) ProtoMessage() {}

func (x *Anime) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Anime.ProtoReflect.Descriptor instead.
func (*Anime) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{19}
}

func (x *Anime) GetAnilistId() int32 {
	if x != nil {
		return x.AnilistId
	}
	return 0
}

func (x *Anime) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Anime) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *Anime) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Anime) GetEpisodes() int32 {
	if x != nil {
		return x.Episodes
	}
	return 0
}

func (x *Anime) GetSeasonYear() int32 {
	if x != nil {
		return x.SeasonYear
	}
	return 0
}

func (x *Anime) GetCoverImage() string {
	if x != nil {
		return x.CoverImage
	}
	return ""
}

func (x *Anime) GetTracked() bool {
	if x != nil {
		return x.Tracked
	}
	return false
}

// AnimeList is an ordered set of shows.
type AnimeList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Anime               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnimeList) Reset() {
	*x = AnimeList{}
	mi := &file_admin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnimeList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnimeList) ProtoMessage() {}

func (x *AnimeList) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnimeList.ProtoReflect.Descriptor instead.
func (*AnimeList) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{20}
}

func (x *AnimeList) GetItems() []*Anime {
	if x != nil {
		return x.Items
	}
	return nil
}

// Resume is the structured résumé (wire DTO mirroring internal/resume.Resume).
type Resume struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Location      string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Github        string                 `protobuf:"bytes,5,opt,name=github,proto3" json:"github,omitempty"`
	Linkedin      string                 `protobuf:"bytes,6,opt,name=linkedin,proto3" json:"linkedin,omitempty"`
	Summary       string                 `protobuf:"bytes,7,opt,name=summary,proto3" json:"summary,omitempty"`
	Jobs          []*ResumeJob           `protobuf:"bytes,8,rep,name=jobs,proto3" json:"jobs,omitempty"`
	Skills        []*ResumeSkill         `protobuf:"bytes,9,rep,name=skills,proto3" json:"skills,omitempty"`
	Projects      []*ResumeProject       `protobuf:"bytes,10,rep,name=projects,proto3" json:"projects,omitempty"`
	Education     []string               `protobuf:"bytes,11,rep,name=education,proto3" json:"education,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resume) Reset() {
	*x = Resume{}
	mi := &file_admin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resume) ProtoMessage() {}

func (x *Resume) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resume.ProtoReflect.Descriptor instead.
func (*Resume) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{21}
}

func (x *Resume) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Resume) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Resume) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Resume) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Resume) GetGithub() string {
	if x != nil {
		return x.Github
	}
	return ""
}

func (x *Resume) GetLinkedin() string {
	if x != nil {
		return x.Linkedin
	}
	return ""
}

func (x *Resume) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Resume) GetJobs() []*ResumeJob {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *Resume) GetSkills() []*ResumeSkill {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *Resume) GetProjects() []*ResumeProject {
	if x != nil {
		return x.Projects
	}
	return nil
}

func (x *Resume) GetEducation() []string {
	if x != nil {
		return x.Education
	}
	return nil
}

// ResumeJob is one work entry.
type ResumeJob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Org           string                 `protobuf:"bytes,2,opt,name=org,proto3" json:"org,omitempty"`
	Dates         string                 `protobuf:"bytes,3,opt,name=dates,proto3" json:"dates,omitempty"`
	Bullets       []string               `protobuf:"bytes,4,rep,name=bullets,proto3" json:"bullets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeJob) Reset() {
	*x = ResumeJob{}
	mi := &file_admin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeJob) ProtoMessage() {}

func (x *ResumeJob) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeJob.ProtoReflect.Descriptor instead.
func (*ResumeJob) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{22}
}

func (x *ResumeJob) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ResumeJob) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *ResumeJob) GetDates() string {
	if x != nil {
		return x.Dates
	}
	return ""
}

func (x *ResumeJob) GetBullets() []string {
	if x != nil {
		return x.Bullets
	}
	return nil
}

// ResumeSkill is a labeled skills row.
type ResumeSkill struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Items         string                 `protobuf:"bytes,2,opt,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeSkill) Reset() {
	*x = ResumeSkill{}
	mi := &file_admin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeSkill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeSkill) ProtoMessage() {}

func (x *ResumeSkill) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeSkill.ProtoReflect.Descriptor instead.
func (*ResumeSkill) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{23}
}

func (x *ResumeSkill) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ResumeSkill) GetItems() string {
	if x != nil {
		return x.Items
	}
	return ""
}

// ResumeProject is one selected project.
type ResumeProject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Desc          string                 `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeProject) Reset() {
	*x = ResumeProject{}
	mi := &file_admin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeProject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeProject) ProtoMessage() {}

func (x *ResumeProject) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeProject.ProtoReflect.Descriptor instead.
func (*ResumeProject) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{24}
}

func (x *ResumeProject) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResumeProject) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

// TailorRequest carries the job-posting URL to tailor against.
type TailorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobUrl        string                 `protobuf:"bytes,1,opt,name=job_url,json=jobUrl,proto3" json:"job_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TailorRequest) Reset() {
	*x = TailorRequest{}
	mi := &file_admin_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TailorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TailorRequest) ProtoMessage() {}

func (x *TailorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TailorRequest.ProtoReflect.Descriptor instead.
func (*TailorRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{25}
}

func (x *TailorRequest) GetJobUrl() string {
	if x != nil {
		return x.JobUrl
	}
	return ""
}

// TailorResult is the full output of a tailoring pass: the tailored résumé, the signals the tool
// extracted from the posting, and the rationale for each choice.
type TailorResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resume        *Resume                `protobuf:"bytes,1,opt,name=resume,proto3" json:"resume,omitempty"`
	Job           *JobAnalysis           `protobuf:"bytes,2,opt,name=job,proto3" json:"job,omitempty"`
	Rationales    []*Rationale           `protobuf:"bytes,3,rep,name=rationales,proto3" json:"rationales,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TailorResult) Reset() {
	*x = TailorResult{}
	mi := &file_admin_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TailorResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TailorResult) ProtoMessage() {}

func (x *TailorResult) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TailorResult.ProtoReflect.Descriptor instead.
func (*TailorResult) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{26}
}

func (x *TailorResult) GetResume() *Resume {
	if x != nil {
		return x.Resume
	}
	return nil
}

func (x *TailorResult) GetJob() *JobAnalysis {
	if x != nil {
		return x.Job
	}
	return nil
}

func (x *TailorResult) GetRationales() []*Rationale {
	if x != nil {
		return x.Rationales
	}
	return nil
}

// JobAnalysis is what the tool pulled out of the job posting.
type JobAnalysis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Company       string                 `protobuf:"bytes,2,opt,name=company,proto3" json:"company,omitempty"`
	Keywords      []string               `protobuf:"bytes,3,rep,name=keywords,proto3" json:"keywords,omitempty"`         // key skills/terms the posting emphasizes
	Requirements  []string               `protobuf:"bytes,4,rep,name=requirements,proto3" json:"requirements,omitempty"` // key requirements / responsibilities
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobAnalysis) Reset() {
	*x = JobAnalysis{}
	mi := &file_admin_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobAnalysis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobAnalysis) ProtoMessage() {}

func (x *JobAnalysis) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobAnalysis.ProtoReflect.Descriptor instead.
func (*JobAnalysis) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{27}
}

func (x *JobAnalysis) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *JobAnalysis) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *JobAnalysis) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

func (x *JobAnalysis) GetRequirements() []string {
	if x != nil {
		return x.Requirements
	}
	return nil
}

// Rationale explains one tailoring decision: what was emphasized and why.
type Rationale struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Focus         string                 `protobuf:"bytes,1,opt,name=focus,proto3" json:"focus,omitempty"`   // what changed / was emphasized (e.g. "Summary", "UKG bullet on React")
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"` // why, tied to a job signal
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rationale) Reset() {
	*x = Rationale{}
	mi := &file_admin_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rationale) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rationale) ProtoMessage() {}

func (x *Rationale) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rationale.ProtoReflect.Descriptor instead.
func (*Rationale) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{28}
}

func (x *Rationale) GetFocus() string {
	if x != nil {
		return x.Focus
	}
	return ""
}

func (x *Rationale) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// CashFluxPendingDevice is one unresolved device-pairing request awaiting admin approval or rejection.
type CashFluxPendingDevice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	RequestedAt   int64                  `protobuf:"varint,3,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"` // unix seconds
	ExpiresAt     int64                  `protobuf:"varint,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`       // unix seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CashFluxPendingDevice) Reset() {
	*x = CashFluxPendingDevice{}
	mi := &file_admin_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CashFluxPendingDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CashFluxPendingDevice) ProtoMessage() {}

func (x *CashFluxPendingDevice) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CashFluxPendingDevice.ProtoReflect.Descriptor instead.
func (*CashFluxPendingDevice) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{29}
}

func (x *CashFluxPendingDevice) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *CashFluxPendingDevice) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *CashFluxPendingDevice) GetRequestedAt() int64 {
	if x != nil {
		return x.RequestedAt
	}
	return 0
}

func (x *CashFluxPendingDevice) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

// CashFluxPendingDeviceList is unresolved pairing requests, oldest first.
type CashFluxPendingDeviceList struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Items         []*CashFluxPendingDevice `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CashFluxPendingDeviceList) Reset() {
	*x = CashFluxPendingDeviceList{}
	mi := &file_admin_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CashFluxPendingDeviceList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CashFluxPendingDeviceList) ProtoMessage() {}

func (x *CashFluxPendingDeviceList) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CashFluxPendingDeviceList.ProtoReflect.Descriptor instead.
func (*CashFluxPendingDeviceList) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{30}
}

func (x *CashFluxPendingDeviceList) GetItems() []*CashFluxPendingDevice {
	if x != nil {
		return x.Items
	}
	return nil
}

// CashFluxApprovePairingRequest identifies the pending device to approve.
type CashFluxApprovePairingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CashFluxApprovePairingRequest) Reset() {
	*x = CashFluxApprovePairingRequest{}
	mi := &file_admin_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CashFluxApprovePairingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CashFluxApprovePairingRequest) ProtoMessage() {}

func (x *CashFluxApprovePairingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CashFluxApprovePairingRequest.ProtoReflect.Descriptor instead.
func (*CashFluxApprovePairingRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{31}
}

func (x *CashFluxApprovePairingRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

// CashFluxApprovePairingResponse reports whether the approval landed. pairing_code is set only when
// approved is true — the admin reads it to (or cross-checks it against) the person on the device.
type CashFluxApprovePairingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Approved      bool                   `protobuf:"varint,1,opt,name=approved,proto3" json:"approved,omitempty"`
	PairingCode   string                 `protobuf:"bytes,2,opt,name=pairing_code,json=pairingCode,proto3" json:"pairing_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CashFluxApprovePairingResponse) Reset() {
	*x = CashFluxApprovePairingResponse{}
	mi := &file_admin_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CashFluxApprovePairingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CashFluxApprovePairingResponse) ProtoMessage() {}

func (x *CashFluxApprovePairingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CashFluxApprovePairingResponse.ProtoReflect.Descriptor instead.
func (*CashFluxApprovePairingResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{32}
}

func (x *CashFluxApprovePairingResponse) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

func (x *CashFluxApprovePairingResponse) GetPairingCode() string {
	if x != nil {
		return x.PairingCode
	}
	return ""
}

// CashFluxRejectPairingRequest identifies the pending device to reject.
type CashFluxRejectPairingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CashFluxRejectPairingRequest) Reset() {
	*x = CashFluxRejectPairingRequest{}
	mi := &file_admin_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CashFluxRejectPairingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CashFluxRejectPairingRequest) ProtoMessage() {}

func (x *CashFluxRejectPairingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CashFluxRejectPairingRequest.ProtoReflect.Descriptor instead.
func (*CashFluxRejectPairingRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{33}
}

func (x *CashFluxRejectPairingRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

// CashFluxRejectPairingResponse reports whether the rejection landed.
type CashFluxRejectPairingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rejected      bool                   `protobuf:"varint,1,opt,name=rejected,proto3" json:"rejected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CashFluxRejectPairingResponse) Reset() {
	*x = CashFluxRejectPairingResponse{}
	mi := &file_admin_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CashFluxRejectPairingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CashFluxRejectPairingResponse) ProtoMessage() {}

func (x *CashFluxRejectPairingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CashFluxRejectPairingResponse.ProtoReflect.Descriptor instead.
func (*CashFluxRejectPairingResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{34}
}

func (x *CashFluxRejectPairingResponse) GetRejected() bool {
	if x != nil {
		return x.Rejected
	}
	return false
}

// CashFluxListUsersRequest pages through enrolled CashFlux accounts. limit <= 0 defaults server-side;
// offset < 0 is treated as 0.
type CashFluxListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CashFluxListUsersRequest) Reset() {
	*x = CashFluxListUsersRequest{}
	mi := &file_admin_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CashFluxListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CashFluxListUsersRequest) ProtoMessage() {}

func (x *CashFluxListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CashFluxListUsersRequest.ProtoReflect.Descriptor instead.
func (*CashFluxListUsersRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{35}
}

func (x *CashFluxListUsersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *CashFluxListUsersRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// CashFluxUser is one enrolled CashFlux account, with its current calendar month's request volume.
type CashFluxUser struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Provider           string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	Email              string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	CreatedAt          int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // unix seconds
	SubscriptionPlan   string                 `protobuf:"bytes,5,opt,name=subscription_plan,json=subscriptionPlan,proto3" json:"subscription_plan,omitempty"`
	SubscriptionStatus string                 `protobuf:"bytes,6,opt,name=subscription_status,json=subscriptionStatus,proto3" json:"subscription_status,omitempty"`
	RequestsThisMonth  int64                  `protobuf:"varint,7,opt,name=requests_this_month,json=requestsThisMonth,proto3" json:"requests_this_month,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CashFluxUser) Reset() {
	*x = CashFluxUser{}
	mi := &file_admin_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CashFluxUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CashFluxUser) ProtoMessage() {}

func (x *CashFluxUser) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CashFluxUser.ProtoReflect.Descriptor instead.
func (*CashFluxUser) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{36}
}

func (x *CashFluxUser) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CashFluxUser) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *CashFluxUser) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CashFluxUser) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *CashFluxUser) GetSubscriptionPlan() string {
	if x != nil {
		return x.SubscriptionPlan
	}
	return ""
}

func (x *CashFluxUser) GetSubscriptionStatus() string {
	if x != nil {
		return x.SubscriptionStatus
	}
	return ""
}

func (x *CashFluxUser) GetRequestsThisMonth() int64 {
	if x != nil {
		return x.RequestsThisMonth
	}
	return 0
}

// CashFluxUserList is one page of enrolled accounts, newest first.
type CashFluxUserList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*CashFluxUser        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CashFluxUserList) Reset() {
	*x = CashFluxUserList{}
	mi := &file_admin_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CashFluxUserList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CashFluxUserList) ProtoMessage() {}

func (x *CashFluxUserList) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CashFluxUserList.ProtoReflect.Descriptor instead.
func (*CashFluxUserList) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{37}
}

func (x *CashFluxUserList) GetItems() []*CashFluxUser {
	if x != nil {
		return x.Items
	}
	return nil
}

// CashFluxStorageStats reports on-disk storage usage: the SQLite database's own size and the total
// size of every stored artifact blob, in bytes.
type CashFluxStorageStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DbBytes       int64                  `protobuf:"varint,1,opt,name=db_bytes,json=dbBytes,proto3" json:"db_bytes,omitempty"`
	BlobBytes     int64                  `protobuf:"varint,2,opt,name=blob_bytes,json=blobBytes,proto3" json:"blob_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CashFluxStorageStats) Reset() {
	*x = CashFluxStorageStats{}
	mi := &file_admin_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CashFluxStorageStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CashFluxStorageStats) ProtoMessage() {}

func (x *CashFluxStorageStats) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CashFluxStorageStats.ProtoReflect.Descriptor instead.
func (*CashFluxStorageStats) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{38}
}

func (x *CashFluxStorageStats) GetDbBytes() int64 {
	if x != nil {
		return x.DbBytes
	}
	return 0
}

func (x *CashFluxStorageStats) GetBlobBytes() int64 {
	if x != nil {
		return x.BlobBytes
	}
	return 0
}

var File_admin_proto protoreflect.FileDescriptor

const file_admin_proto_rawDesc = "" +
	"\n" +
	"\vadmin.proto\x12\asite.v1\x1a\n" +
	"site.proto\" \n" +
	"\n" +
	"PromptText\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"s\n" +
	"\vPostPreview\x12\x12\n" +
	"\x04body\x18\x01 \x01(\tR\x04body\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x10\n" +
	"\x03rss\x18\x03 \x01(\tR\x03rss\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12\x12\n" +
	"\x04news\x18\x05 \x01(\tR\x04news\"\x86\x01\n" +
	"\vSlackConfig\x12\x1f\n" +
	"\vwebhook_url\x18\x01 \x01(\tR\n" +
	"webhookUrl\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\x12\x1f\n" +
	"\vwebhook_set\x18\x03 \x01(\bR\n" +
	"webhookSet\x12\x1b\n" +
	"\tpost_hour\x18\x04 \x01(\x05R\bpostHour\"\x1d\n" +
	"\vTailoringId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xa3\x01\n" +
	"\rTailoringMeta\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\ajob_url\x18\x02 \x01(\tR\x06jobUrl\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\acompany\x18\x04 \x01(\tR\acompany\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1a\n" +
	"\bkeywords\x18\x06 \x03(\tR\bkeywords\"=\n" +
	"\rTailoringList\x12,\n" +
	"\x05items\x18\x01 \x03(\v2\x16.site.v1.TailoringMetaR\x05items\"l\n" +
	"\bSettings\x12$\n" +
	"\x0eopenai_api_key\x18\x01 \x01(\tR\fopenaiApiKey\x12!\n" +
	"\fopenai_model\x18\x02 \x01(\tR\vopenaiModel\x12\x17\n" +
	"\akey_set\x18\x03 \x01(\bR\x06keySet\"#\n" +
	"\tModelList\x12\x16\n" +
	"\x06models\x18\x01 \x03(\tR\x06models\"\a\n" +
	"\x05Empty\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"2\n" +
	"\n" +
	"LoginReply\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"V\n" +
	"\x0eAuthStateReply\x12\x1f\n" +
	"\vneeds_setup\x18\x01 \x01(\bR\n" +
	"needsSetup\x12#\n" +
	"\rrecovery_hint\x18\x02 \x01(\tR\frecoveryHint\"{\n" +
	"\fSetupRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x12\n" +
	"\x04hint\x18\x03 \x01(\tR\x04hint\x12\x1f\n" +
	"\vsetup_token\x18\x04 \x01(\tR\n" +
	"setupToken\"q\n" +
	"\n" +
	"SetupReply\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12'\n" +
	"\x0frecovery_phrase\x18\x03 \x01(\tR\x0erecoveryPhrase\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"Z\n" +
	"\fResetRequest\x12'\n" +
	"\x0frecovery_phrase\x18\x01 \x01(\tR\x0erecoveryPhrase\x12!\n" +
	"\fnew_password\x18\x02 \x01(\tR\vnewPassword\"[\n" +
	"\n" +
	"ResetReply\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12'\n" +
	"\x0frecovery_phrase\x18\x02 \x01(\tR\x0erecoveryPhrase\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"%\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"(\n" +
	"\aAnimeId\x12\x1d\n" +
	"\n" +
	"anilist_id\x18\x01 \x01(\x05R\tanilistId\"&\n" +
	"\n" +
	"CheckReply\x12\x18\n" +
	"\aupdated\x18\x01 \x01(\x05R\aupdated\"\xe4\x01\n" +
	"\x05Anime\x12\x1d\n" +
	"\n" +
	"anilist_id\x18\x01 \x01(\x05R\tanilistId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1a\n" +
	"\bepisodes\x18\x05 \x01(\x05R\bepisodes\x12\x1f\n" +
	"\vseason_year\x18\x06 \x01(\x05R\n" +
	"seasonYear\x12\x1f\n" +
	"\vcover_image\x18\a \x01(\tR\n" +
	"coverImage\x12\x18\n" +
	"\atracked\x18\b \x01(\bR\atracked\"1\n" +
	"\tAnimeList\x12$\n" +
	"\x05items\x18\x01 \x03(\v2\x0e.site.v1.AnimeR\x05items\"\xda\x02\n" +
	"\x06Resume\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x16\n" +
	"\x06github\x18\x05 \x01(\tR\x06github\x12\x1a\n" +
	"\blinkedin\x18\x06 \x01(\tR\blinkedin\x12\x18\n" +
	"\asummary\x18\a \x01(\tR\asummary\x12&\n" +
	"\x04jobs\x18\b \x03(\v2\x12.site.v1.ResumeJobR\x04jobs\x12,\n" +
	"\x06skills\x18\t \x03(\v2\x14.site.v1.ResumeSkillR\x06skills\x122\n" +
	"\bprojects\x18\n" +
	" \x03(\v2\x16.site.v1.ResumeProjectR\bprojects\x12\x1c\n" +
	"\teducation\x18\v \x03(\tR\teducation\"a\n" +
	"\tResumeJob\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x10\n" +
	"\x03org\x18\x02 \x01(\tR\x03org\x12\x14\n" +
	"\x05dates\x18\x03 \x01(\tR\x05dates\x12\x18\n" +
	"\abullets\x18\x04 \x03(\tR\abullets\"9\n" +
	"\vResumeSkill\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x14\n" +
	"\x05items\x18\x02 \x01(\tR\x05items\"7\n" +
	"\rResumeProject\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04desc\x18\x02 \x01(\tR\x04desc\"(\n" +
	"\rTailorRequest\x12\x17\n" +
	"\ajob_url\x18\x01 \x01(\tR\x06jobUrl\"\x93\x01\n" +
	"\fTailorResult\x12'\n" +
	"\x06resume\x18\x01 \x01(\v2\x0f.site.v1.ResumeR\x06resume\x12&\n" +
	"\x03job\x18\x02 \x01(\v2\x14.site.v1.JobAnalysisR\x03job\x122\n" +
	"\n" +
	"rationales\x18\x03 \x03(\v2\x12.site.v1.RationaleR\n" +
	"rationales\"}\n" +
	"\vJobAnalysis\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acompany\x18\x02 \x01(\tR\acompany\x12\x1a\n" +
	"\bkeywords\x18\x03 \x03(\tR\bkeywords\x12\"\n" +
	"\frequirements\x18\x04 \x03(\tR\frequirements\"9\n" +
	"\tRationale\x12\x14\n" +
	"\x05focus\x18\x01 \x01(\tR\x05focus\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x8c\x01\n" +
	"\x15CashFluxPendingDevice\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12!\n" +
	"\frequested_at\x18\x03 \x01(\x03R\vrequestedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\x03R\texpiresAt\"Q\n" +
	"\x19CashFluxPendingDeviceList\x124\n" +
	"\x05items\x18\x01 \x03(\v2\x1e.site.v1.CashFluxPendingDeviceR\x05items\"<\n" +
	"\x1dCashFluxApprovePairingRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\"_\n" +
	"\x1eCashFluxApprovePairingResponse\x12\x1a\n" +
	"\bapproved\x18\x01 \x01(\bR\bapproved\x12!\n" +
	"\fpairing_code\x18\x02 \x01(\tR\vpairingCode\";\n" +
	"\x1cCashFluxRejectPairingRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\";\n" +
	"\x1dCashFluxRejectPairingResponse\x12\x1a\n" +
	"\brejected\x18\x01 \x01(\bR\brejected\"H\n" +
	"\x18CashFluxListUsersRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"\xfd\x01\n" +
	"\fCashFluxUser\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\x12+\n" +
	"\x11subscription_plan\x18\x05 \x01(\tR\x10subscriptionPlan\x12/\n" +
	"\x13subscription_status\x18\x06 \x01(\tR\x12subscriptionStatus\x12.\n" +
	"\x13requests_this_month\x18\a \x01(\x03R\x11requestsThisMonth\"?\n" +
	"\x10CashFluxUserList\x12+\n" +
	"\x05items\x18\x01 \x03(\v2\x15.site.v1.CashFluxUserR\x05items\"P\n" +
	"\x14CashFluxStorageStats\x12\x19\n" +
	"\bdb_bytes\x18\x01 \x01(\x03R\adbBytes\x12\x1d\n" +
	"\n" +
	"blob_bytes\x18\x02 \x01(\x03R\tblobBytes2\xb9\x0e\n" +
	"\fAdminService\x123\n" +
	"\x05Login\x12\x15.site.v1.LoginRequest\x1a\x13.site.v1.LoginReply\x124\n" +
	"\tAuthState\x12\x0e.site.v1.Empty\x1a\x17.site.v1.AuthStateReply\x123\n" +
	"\x05Setup\x12\x15.site.v1.SetupRequest\x1a\x13.site.v1.SetupReply\x12;\n" +
	"\rResetPassword\x12\x15.site.v1.ResetRequest\x1a\x13.site.v1.ResetReply\x129\n" +
	"\vSearchAnime\x12\x16.site.v1.SearchRequest\x1a\x12.site.v1.AnimeList\x121\n" +
	"\vListTracked\x12\x0e.site.v1.Empty\x1a\x12.site.v1.AnimeList\x12,\n" +
	"\n" +
	"TrackAnime\x12\x10.site.v1.AnimeId\x1a\f.site.v1.Ack\x12.\n" +
	"\fUntrackAnime\x12\x10.site.v1.AnimeId\x1a\f.site.v1.Ack\x126\n" +
	"\x0fRunReleaseCheck\x12\x0e.site.v1.Empty\x1a\x13.site.v1.CheckReply\x12,\n" +
	"\tGetResume\x12\x0e.site.v1.Empty\x1a\x0f.site.v1.Resume\x12,\n" +
	"\vApplyResume\x12\x0f.site.v1.Resume\x1a\f.site.v1.Ack\x12=\n" +
	"\fTailorResume\x12\x16.site.v1.TailorRequest\x1a\x15.site.v1.TailorResult\x120\n" +
	"\vGetSettings\x12\x0e.site.v1.Empty\x1a\x11.site.v1.Settings\x12/\n" +
	"\fSaveSettings\x12\x11.site.v1.Settings\x1a\f.site.v1.Ack\x120\n" +
	"\n" +
	"ListModels\x12\x0e.site.v1.Empty\x1a\x12.site.v1.ModelList\x129\n" +
	"\x10GetLastTailoring\x12\x0e.site.v1.Empty\x1a\x15.site.v1.TailorResult\x120\n" +
	"\rGetBaseResume\x12\x0e.site.v1.Empty\x1a\x0f.site.v1.Resume\x128\n" +
	"\x0eListTailorings\x12\x0e.site.v1.Empty\x1a\x16.site.v1.TailoringList\x12;\n" +
	"\fGetTailoring\x12\x14.site.v1.TailoringId\x1a\x15.site.v1.TailorResult\x125\n" +
	"\x0fDeleteTailoring\x12\x14.site.v1.TailoringId\x1a\f.site.v1.Ack\x120\n" +
	"\tGetPrompt\x12\x0e.site.v1.Empty\x1a\x13.site.v1.PromptText\x12/\n" +
	"\n" +
	"SavePrompt\x12\x13.site.v1.PromptText\x1a\f.site.v1.Ack\x129\n" +
	"\fDryRunPrompt\x12\x13.site.v1.PromptText\x1a\x14.site.v1.PostPreview\x126\n" +
	"\x0eGetSlackConfig\x12\x0e.site.v1.Empty\x1a\x14.site.v1.SlackConfig\x125\n" +
	"\x0fSaveSlackConfig\x12\x14.site.v1.SlackConfig\x1a\f.site.v1.Ack\x12.\n" +
	"\x0ePostToSlackNow\x12\x0e.site.v1.Empty\x1a\f.site.v1.Ack\x12P\n" +
	"\x1aListCashFluxPendingDevices\x12\x0e.site.v1.Empty\x1a\".site.v1.CashFluxPendingDeviceList\x12i\n" +
	"\x16ApproveCashFluxPairing\x12&.site.v1.CashFluxApprovePairingRequest\x1a'.site.v1.CashFluxApprovePairingResponse\x12f\n" +
	"\x15RejectCashFluxPairing\x12%.site.v1.CashFluxRejectPairingRequest\x1a&.site.v1.CashFluxRejectPairingResponse\x12Q\n" +
	"\x11ListCashFluxUsers\x12!.site.v1.CashFluxListUsersRequest\x1a\x19.site.v1.CashFluxUserList\x12H\n" +
	"\x17GetCashFluxStorageStats\x12\x0e.site.v1.Empty\x1a\x1d.site.v1.CashFluxStorageStatsB;Z9github.com/monstercameron/earlcameron/proto/sitepb;sitepbb\x06proto3"

var (
	file_admin_proto_rawDescOnce sync.Once
	file_admin_proto_rawDescData []byte
)

func file_admin_proto_rawDescGZIP() []byte {
	file_admin_proto_rawDescOnce.Do(func() {
		file_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_proto_rawDesc), len(file_admin_proto_rawDesc)))
	})
	return file_admin_proto_rawDescData
}

var file_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 39)
var file_admin_proto_goTypes = []any{
	(*PromptText)(nil),                     // 0: site.v1.PromptText
	(*PostPreview)(nil),                    // 1: site.v1.PostPreview
	(*SlackConfig)(nil),                    // 2: site.v1.SlackConfig
	(*TailoringId)(nil),                    // 3: site.v1.TailoringId
	(*TailoringMeta)(nil),                  // 4: site.v1.TailoringMeta
	(*TailoringList)(nil),                  // 5: site.v1.TailoringList
	(*Settings)(nil),                       // 6: site.v1.Settings
	(*ModelList)(nil),                      // 7: site.v1.ModelList
	(*Empty)(nil),                          // 8: site.v1.Empty
	(*LoginRequest)(nil),                   // 9: site.v1.LoginRequest
	(*LoginReply)(nil),                     // 10: site.v1.LoginReply
	(*AuthStateReply)(nil),                 // 11: site.v1.AuthStateReply
	(*SetupRequest)(nil),                   // 12: site.v1.SetupRequest
	(*SetupReply)(nil),                     // 13: site.v1.SetupReply
	(*ResetRequest)(nil),                   // 14: site.v1.ResetRequest
	(*ResetReply)(nil),                     // 15: site.v1.ResetReply
	(*SearchRequest)(nil),                  // 16: site.v1.SearchRequest
	(*AnimeId)(nil),                        // 17: site.v1.AnimeId
	(*CheckReply)(nil),                     // 18: site.v1.CheckReply
	(*Anime)(nil),                          // 19: site.v1.Anime
	(*AnimeList)(nil),                      // 20: site.v1.AnimeList
	(*Resume)(nil),                         // 21: site.v1.Resume
	(*ResumeJob)(nil),                      // 22: site.v1.ResumeJob
	(*ResumeSkill)(nil),                    // 23: site.v1.ResumeSkill
	(*ResumeProject)(nil),                  // 24: site.v1.ResumeProject
	(*TailorRequest)(nil),                  // 25: site.v1.TailorRequest
	(*TailorResult)(nil),                   // 26: site.v1.TailorResult
	(*JobAnalysis)(nil),                    // 27: site.v1.JobAnalysis
	(*Rationale)(nil),                      // 28: site.v1.Rationale
	(*CashFluxPendingDevice)(nil),          // 29: site.v1.CashFluxPendingDevice
	(*CashFluxPendingDeviceList)(nil),      // 30: site.v1.CashFluxPendingDeviceList
	(*CashFluxApprovePairingRequest)(nil),  // 31: site.v1.CashFluxApprovePairingRequest
	(*CashFluxApprovePairingResponse)(nil), // 32: site.v1.CashFluxApprovePairingResponse
	(*CashFluxRejectPairingRequest)(nil),   // 33: site.v1.CashFluxRejectPairingRequest
	(*CashFluxRejectPairingResponse)(nil),  // 34: site.v1.CashFluxRejectPairingResponse
	(*CashFluxListUsersRequest)(nil),       // 35: site.v1.CashFluxListUsersRequest
	(*CashFluxUser)(nil),                   // 36: site.v1.CashFluxUser
	(*CashFluxUserList)(nil),               // 37: site.v1.CashFluxUserList
	(*CashFluxStorageStats)(nil),           // 38: site.v1.CashFluxStorageStats
	(*Ack)(nil),                            // 39: site.v1.Ack
}
var file_admin_proto_depIdxs = []int32{
	4,  // 0: site.v1.TailoringList.items:type_name -> site.v1.TailoringMeta
	19, // 1: site.v1.AnimeList.items:type_name -> site.v1.Anime
	22, // 2: site.v1.Resume.jobs:type_name -> site.v1.ResumeJob
	23, // 3: site.v1.Resume.skills:type_name -> site.v1.ResumeSkill
	24, // 4: site.v1.Resume.projects:type_name -> site.v1.ResumeProject
	21, // 5: site.v1.TailorResult.resume:type_name -> site.v1.Resume
	27, // 6: site.v1.TailorResult.job:type_name -> site.v1.JobAnalysis
	28, // 7: site.v1.TailorResult.rationales:type_name -> site.v1.Rationale
	29, // 8: site.v1.CashFluxPendingDeviceList.items:type_name -> site.v1.CashFluxPendingDevice
	36, // 9: site.v1.CashFluxUserList.items:type_name -> site.v1.CashFluxUser
	9,  // 10: site.v1.AdminService.Login:input_type -> site.v1.LoginRequest
	8,  // 11: site.v1.AdminService.AuthState:input_type -> site.v1.Empty
	12, // 12: site.v1.AdminService.Setup:input_type -> site.v1.SetupRequest
	14, // 13: site.v1.AdminService.ResetPassword:input_type -> site.v1.ResetRequest
	16, // 14: site.v1.AdminService.SearchAnime:input_type -> site.v1.SearchRequest
	8,  // 15: site.v1.AdminService.ListTracked:input_type -> site.v1.Empty
	17, // 16: site.v1.AdminService.TrackAnime:input_type -> site.v1.AnimeId
	17, // 17: site.v1.AdminService.UntrackAnime:input_type -> site.v1.AnimeId
	8,  // 18: site.v1.AdminService.RunReleaseCheck:input_type -> site.v1.Empty
	8,  // 19: site.v1.AdminService.GetResume:input_type -> site.v1.Empty
	21, // 20: site.v1.AdminService.ApplyResume:input_type -> site.v1.Resume
	25, // 21: site.v1.AdminService.TailorResume:input_type -> site.v1.TailorRequest
	8,  // 22: site.v1.AdminService.GetSettings:input_type -> site.v1.Empty
	6,  // 23: site.v1.AdminService.SaveSettings:input_type -> site.v1.Settings
	8,  // 24: site.v1.AdminService.ListModels:input_type -> site.v1.Empty
	8,  // 25: site.v1.AdminService.GetLastTailoring:input_type -> site.v1.Empty
	8,  // 26: site.v1.AdminService.GetBaseResume:input_type -> site.v1.Empty
	8,  // 27: site.v1.AdminService.ListTailorings:input_type -> site.v1.Empty
	3,  // 28: site.v1.AdminService.GetTailoring:input_type -> site.v1.TailoringId
	3,  // 29: site.v1.AdminService.DeleteTailoring:input_type -> site.v1.TailoringId
	8,  // 30: site.v1.AdminService.GetPrompt:input_type -> site.v1.Empty
	0,  // 31: site.v1.AdminService.SavePrompt:input_type -> site.v1.PromptText
	0,  // 32: site.v1.AdminService.DryRunPrompt:input_type -> site.v1.PromptText
	8,  // 33: site.v1.AdminService.GetSlackConfig:input_type -> site.v1.Empty
	2,  // 34: site.v1.AdminService.SaveSlackConfig:input_type -> site.v1.SlackConfig
	8,  // 35: site.v1.AdminService.PostToSlackNow:input_type -> site.v1.Empty
	8,  // 36: site.v1.AdminService.ListCashFluxPendingDevices:input_type -> site.v1.Empty
	31, // 37: site.v1.AdminService.ApproveCashFluxPairing:input_type -> site.v1.CashFluxApprovePairingRequest
	33, // 38: site.v1.AdminService.RejectCashFluxPairing:input_type -> site.v1.CashFluxRejectPairingRequest
	35, // 39: site.v1.AdminService.ListCashFluxUsers:input_type -> site.v1.CashFluxListUsersRequest
	8,  // 40: site.v1.AdminService.GetCashFluxStorageStats:input_type -> site.v1.Empty
	10, // 41: site.v1.AdminService.Login:output_type -> site.v1.LoginReply
	11, // 42: site.v1.AdminService.AuthState:output_type -> site.v1.AuthStateReply
	13, // 43: site.v1.AdminService.Setup:output_type -> site.v1.SetupReply
	15, // 44: site.v1.AdminService.ResetPassword:output_type -> site.v1.ResetReply
	20, // 45: site.v1.AdminService.SearchAnime:output_type -> site.v1.AnimeList
	20, // 46: site.v1.AdminService.ListTracked:output_type -> site.v1.AnimeList
	39, // 47: site.v1.AdminService.TrackAnime:output_type -> site.v1.Ack
	39, // 48: site.v1.AdminService.UntrackAnime:output_type -> site.v1.Ack
	18, // 49: site.v1.AdminService.RunReleaseCheck:output_type -> site.v1.CheckReply
	21, // 50: site.v1.AdminService.GetResume:output_type -> site.v1.Resume
	39, // 51: site.v1.AdminService.ApplyResume:output_type -> site.v1.Ack
	26, // 52: site.v1.AdminService.TailorResume:output_type -> site.v1.TailorResult
	6,  // 53: site.v1.AdminService.GetSettings:output_type -> site.v1.Settings
	39, // 54: site.v1.AdminService.SaveSettings:output_type -> site.v1.Ack
	7,  // 55: site.v1.AdminService.ListModels:output_type -> site.v1.ModelList
	26, // 56: site.v1.AdminService.GetLastTailoring:output_type -> site.v1.TailorResult
	21, // 57: site.v1.AdminService.GetBaseResume:output_type -> site.v1.Resume
	5,  // 58: site.v1.AdminService.ListTailorings:output_type -> site.v1.TailoringList
	26, // 59: site.v1.AdminService.GetTailoring:output_type -> site.v1.TailorResult
	39, // 60: site.v1.AdminService.DeleteTailoring:output_type -> site.v1.Ack
	0,  // 61: site.v1.AdminService.GetPrompt:output_type -> site.v1.PromptText
	39, // 62: site.v1.AdminService.SavePrompt:output_type -> site.v1.Ack
	1,  // 63: site.v1.AdminService.DryRunPrompt:output_type -> site.v1.PostPreview
	2,  // 64: site.v1.AdminService.GetSlackConfig:output_type -> site.v1.SlackConfig
	39, // 65: site.v1.AdminService.SaveSlackConfig:output_type -> site.v1.Ack
	39, // 66: site.v1.AdminService.PostToSlackNow:output_type -> site.v1.Ack
	30, // 67: site.v1.AdminService.ListCashFluxPendingDevices:output_type -> site.v1.CashFluxPendingDeviceList
	32, // 68: site.v1.AdminService.ApproveCashFluxPairing:output_type -> site.v1.CashFluxApprovePairingResponse
	34, // 69: site.v1.AdminService.RejectCashFluxPairing:output_type -> site.v1.CashFluxRejectPairingResponse
	37, // 70: site.v1.AdminService.ListCashFluxUsers:output_type -> site.v1.CashFluxUserList
	38, // 71: site.v1.AdminService.GetCashFluxStorageStats:output_type -> site.v1.CashFluxStorageStats
	41, // [41:72] is the sub-list for method output_type
	10, // [10:41] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_admin_proto_init() }
func file_admin_proto_init() {
	if File_admin_proto != nil {
		return
	}
	file_site_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_proto_rawDesc), len(file_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   39,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_proto_goTypes,
		DependencyIndexes: file_admin_proto_depIdxs,
		MessageInfos:      file_admin_proto_msgTypes,
	}.Build()
	File_admin_proto = out.File
	file_admin_proto_goTypes = nil
	file_admin_proto_depIdxs = nil
}
