// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: admin.proto

package sitepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Empty is a no-argument request.
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{0}
}

// LoginRequest carries the admin password.
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      string                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{1}
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// LoginReply returns a session token on success.
type LoginReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReply) Reset() {
	*x = LoginReply{}
	mi := &file_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReply) ProtoMessage() {}

func (x *LoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReply.ProtoReflect.Descriptor instead.
func (*LoginReply) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{2}
}

func (x *LoginReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *LoginReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// SearchRequest is an AniList search query.
type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{3}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

// AnimeId identifies one show by its AniList id.
type AnimeId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AnilistId     int32                  `protobuf:"varint,1,opt,name=anilist_id,json=anilistId,proto3" json:"anilist_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnimeId) Reset() {
	*x = AnimeId{}
	mi := &file_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnimeId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnimeId) ProtoMessage() {}

func (x *AnimeId) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnimeId.ProtoReflect.Descriptor instead.
func (*AnimeId) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{4}
}

func (x *AnimeId) GetAnilistId() int32 {
	if x != nil {
		return x.AnilistId
	}
	return 0
}

// CheckReply reports how many tracked shows changed during a release check.
type CheckReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Updated       int32                  `protobuf:"varint,1,opt,name=updated,proto3" json:"updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckReply) Reset() {
	*x = CheckReply{}
	mi := &file_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckReply) ProtoMessage() {}

func (x *CheckReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckReply.ProtoReflect.Descriptor instead.
func (*CheckReply) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{5}
}

func (x *CheckReply) GetUpdated() int32 {
	if x != nil {
		return x.Updated
	}
	return 0
}

// Anime is one show — an AniList search result or a tracked entry.
type Anime struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AnilistId     int32                  `protobuf:"varint,1,opt,name=anilist_id,json=anilistId,proto3" json:"anilist_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Format        string                 `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Episodes      int32                  `protobuf:"varint,5,opt,name=episodes,proto3" json:"episodes,omitempty"`
	SeasonYear    int32                  `protobuf:"varint,6,opt,name=season_year,json=seasonYear,proto3" json:"season_year,omitempty"`
	CoverImage    string                 `protobuf:"bytes,7,opt,name=cover_image,json=coverImage,proto3" json:"cover_image,omitempty"`
	Tracked       bool                   `protobuf:"varint,8,opt,name=tracked,proto3" json:"tracked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Anime) Reset() {
	*x = Anime{}
	mi := &file_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Anime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Anime) ProtoMessage() {}

func (x *Anime) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Anime.ProtoReflect.Descriptor instead.
func (*Anime) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{6}
}

func (x *Anime) GetAnilistId() int32 {
	if x != nil {
		return x.AnilistId
	}
	return 0
}

func (x *Anime) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Anime) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *Anime) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Anime) GetEpisodes() int32 {
	if x != nil {
		return x.Episodes
	}
	return 0
}

func (x *Anime) GetSeasonYear() int32 {
	if x != nil {
		return x.SeasonYear
	}
	return 0
}

func (x *Anime) GetCoverImage() string {
	if x != nil {
		return x.CoverImage
	}
	return ""
}

func (x *Anime) GetTracked() bool {
	if x != nil {
		return x.Tracked
	}
	return false
}

// AnimeList is an ordered set of shows.
type AnimeList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Anime               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnimeList) Reset() {
	*x = AnimeList{}
	mi := &file_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnimeList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnimeList) ProtoMessage() {}

func (x *AnimeList) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnimeList.ProtoReflect.Descriptor instead.
func (*AnimeList) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{7}
}

func (x *AnimeList) GetItems() []*Anime {
	if x != nil {
		return x.Items
	}
	return nil
}

// Resume is the structured résumé (wire DTO mirroring internal/resume.Resume).
type Resume struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Location      string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Github        string                 `protobuf:"bytes,5,opt,name=github,proto3" json:"github,omitempty"`
	Linkedin      string                 `protobuf:"bytes,6,opt,name=linkedin,proto3" json:"linkedin,omitempty"`
	Summary       string                 `protobuf:"bytes,7,opt,name=summary,proto3" json:"summary,omitempty"`
	Jobs          []*ResumeJob           `protobuf:"bytes,8,rep,name=jobs,proto3" json:"jobs,omitempty"`
	Skills        []*ResumeSkill         `protobuf:"bytes,9,rep,name=skills,proto3" json:"skills,omitempty"`
	Projects      []*ResumeProject       `protobuf:"bytes,10,rep,name=projects,proto3" json:"projects,omitempty"`
	Education     []string               `protobuf:"bytes,11,rep,name=education,proto3" json:"education,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resume) Reset() {
	*x = Resume{}
	mi := &file_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resume) ProtoMessage() {}

func (x *Resume) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resume.ProtoReflect.Descriptor instead.
func (*Resume) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{8}
}

func (x *Resume) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Resume) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Resume) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Resume) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Resume) GetGithub() string {
	if x != nil {
		return x.Github
	}
	return ""
}

func (x *Resume) GetLinkedin() string {
	if x != nil {
		return x.Linkedin
	}
	return ""
}

func (x *Resume) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Resume) GetJobs() []*ResumeJob {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *Resume) GetSkills() []*ResumeSkill {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *Resume) GetProjects() []*ResumeProject {
	if x != nil {
		return x.Projects
	}
	return nil
}

func (x *Resume) GetEducation() []string {
	if x != nil {
		return x.Education
	}
	return nil
}

// ResumeJob is one work entry.
type ResumeJob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Org           string                 `protobuf:"bytes,2,opt,name=org,proto3" json:"org,omitempty"`
	Dates         string                 `protobuf:"bytes,3,opt,name=dates,proto3" json:"dates,omitempty"`
	Bullets       []string               `protobuf:"bytes,4,rep,name=bullets,proto3" json:"bullets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeJob) Reset() {
	*x = ResumeJob{}
	mi := &file_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeJob) ProtoMessage() {}

func (x *ResumeJob) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeJob.ProtoReflect.Descriptor instead.
func (*ResumeJob) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{9}
}

func (x *ResumeJob) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ResumeJob) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *ResumeJob) GetDates() string {
	if x != nil {
		return x.Dates
	}
	return ""
}

func (x *ResumeJob) GetBullets() []string {
	if x != nil {
		return x.Bullets
	}
	return nil
}

// ResumeSkill is a labeled skills row.
type ResumeSkill struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Items         string                 `protobuf:"bytes,2,opt,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeSkill) Reset() {
	*x = ResumeSkill{}
	mi := &file_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeSkill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeSkill) ProtoMessage() {}

func (x *ResumeSkill) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeSkill.ProtoReflect.Descriptor instead.
func (*ResumeSkill) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{10}
}

func (x *ResumeSkill) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ResumeSkill) GetItems() string {
	if x != nil {
		return x.Items
	}
	return ""
}

// ResumeProject is one selected project.
type ResumeProject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Desc          string                 `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeProject) Reset() {
	*x = ResumeProject{}
	mi := &file_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeProject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeProject) ProtoMessage() {}

func (x *ResumeProject) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeProject.ProtoReflect.Descriptor instead.
func (*ResumeProject) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{11}
}

func (x *ResumeProject) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResumeProject) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

// TailorRequest carries the job-posting URL to tailor against.
type TailorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobUrl        string                 `protobuf:"bytes,1,opt,name=job_url,json=jobUrl,proto3" json:"job_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TailorRequest) Reset() {
	*x = TailorRequest{}
	mi := &file_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TailorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TailorRequest) ProtoMessage() {}

func (x *TailorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TailorRequest.ProtoReflect.Descriptor instead.
func (*TailorRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{12}
}

func (x *TailorRequest) GetJobUrl() string {
	if x != nil {
		return x.JobUrl
	}
	return ""
}

var File_admin_proto protoreflect.FileDescriptor

const file_admin_proto_rawDesc = "" +
	"\n" +
	"\vadmin.proto\x12\asite.v1\x1a\n" +
	"site.proto\"\a\n" +
	"\x05Empty\"*\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\"2\n" +
	"\n" +
	"LoginReply\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"%\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"(\n" +
	"\aAnimeId\x12\x1d\n" +
	"\n" +
	"anilist_id\x18\x01 \x01(\x05R\tanilistId\"&\n" +
	"\n" +
	"CheckReply\x12\x18\n" +
	"\aupdated\x18\x01 \x01(\x05R\aupdated\"\xe4\x01\n" +
	"\x05Anime\x12\x1d\n" +
	"\n" +
	"anilist_id\x18\x01 \x01(\x05R\tanilistId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1a\n" +
	"\bepisodes\x18\x05 \x01(\x05R\bepisodes\x12\x1f\n" +
	"\vseason_year\x18\x06 \x01(\x05R\n" +
	"seasonYear\x12\x1f\n" +
	"\vcover_image\x18\a \x01(\tR\n" +
	"coverImage\x12\x18\n" +
	"\atracked\x18\b \x01(\bR\atracked\"1\n" +
	"\tAnimeList\x12$\n" +
	"\x05items\x18\x01 \x03(\v2\x0e.site.v1.AnimeR\x05items\"\xda\x02\n" +
	"\x06Resume\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x16\n" +
	"\x06github\x18\x05 \x01(\tR\x06github\x12\x1a\n" +
	"\blinkedin\x18\x06 \x01(\tR\blinkedin\x12\x18\n" +
	"\asummary\x18\a \x01(\tR\asummary\x12&\n" +
	"\x04jobs\x18\b \x03(\v2\x12.site.v1.ResumeJobR\x04jobs\x12,\n" +
	"\x06skills\x18\t \x03(\v2\x14.site.v1.ResumeSkillR\x06skills\x122\n" +
	"\bprojects\x18\n" +
	" \x03(\v2\x16.site.v1.ResumeProjectR\bprojects\x12\x1c\n" +
	"\teducation\x18\v \x03(\tR\teducation\"a\n" +
	"\tResumeJob\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x10\n" +
	"\x03org\x18\x02 \x01(\tR\x03org\x12\x14\n" +
	"\x05dates\x18\x03 \x01(\tR\x05dates\x12\x18\n" +
	"\abullets\x18\x04 \x03(\tR\abullets\"9\n" +
	"\vResumeSkill\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x14\n" +
	"\x05items\x18\x02 \x01(\tR\x05items\"7\n" +
	"\rResumeProject\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04desc\x18\x02 \x01(\tR\x04desc\"(\n" +
	"\rTailorRequest\x12\x17\n" +
	"\ajob_url\x18\x01 \x01(\tR\x06jobUrl2\xae\x03\n" +
	"\fAdminService\x123\n" +
	"\x05Login\x12\x15.site.v1.LoginRequest\x1a\x13.site.v1.LoginReply\x129\n" +
	"\vSearchAnime\x12\x16.site.v1.SearchRequest\x1a\x12.site.v1.AnimeList\x121\n" +
	"\vListTracked\x12\x0e.site.v1.Empty\x1a\x12.site.v1.AnimeList\x12,\n" +
	"\n" +
	"TrackAnime\x12\x10.site.v1.AnimeId\x1a\f.site.v1.Ack\x12.\n" +
	"\fUntrackAnime\x12\x10.site.v1.AnimeId\x1a\f.site.v1.Ack\x126\n" +
	"\x0fRunReleaseCheck\x12\x0e.site.v1.Empty\x1a\x13.site.v1.CheckReply\x12,\n" +
	"\tGetResume\x12\x0e.site.v1.Empty\x1a\x0f.site.v1.Resume\x127\n" +
	"\fTailorResume\x12\x16.site.v1.TailorRequest\x1a\x0f.site.v1.ResumeB;Z9github.com/monstercameron/earlcameron/proto/sitepb;sitepbb\x06proto3"

var (
	file_admin_proto_rawDescOnce sync.Once
	file_admin_proto_rawDescData []byte
)

func file_admin_proto_rawDescGZIP() []byte {
	file_admin_proto_rawDescOnce.Do(func() {
		file_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_proto_rawDesc), len(file_admin_proto_rawDesc)))
	})
	return file_admin_proto_rawDescData
}

var file_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_admin_proto_goTypes = []any{
	(*Empty)(nil),         // 0: site.v1.Empty
	(*LoginRequest)(nil),  // 1: site.v1.LoginRequest
	(*LoginReply)(nil),    // 2: site.v1.LoginReply
	(*SearchRequest)(nil), // 3: site.v1.SearchRequest
	(*AnimeId)(nil),       // 4: site.v1.AnimeId
	(*CheckReply)(nil),    // 5: site.v1.CheckReply
	(*Anime)(nil),         // 6: site.v1.Anime
	(*AnimeList)(nil),     // 7: site.v1.AnimeList
	(*Resume)(nil),        // 8: site.v1.Resume
	(*ResumeJob)(nil),     // 9: site.v1.ResumeJob
	(*ResumeSkill)(nil),   // 10: site.v1.ResumeSkill
	(*ResumeProject)(nil), // 11: site.v1.ResumeProject
	(*TailorRequest)(nil), // 12: site.v1.TailorRequest
	(*Ack)(nil),           // 13: site.v1.Ack
}
var file_admin_proto_depIdxs = []int32{
	6,  // 0: site.v1.AnimeList.items:type_name -> site.v1.Anime
	9,  // 1: site.v1.Resume.jobs:type_name -> site.v1.ResumeJob
	10, // 2: site.v1.Resume.skills:type_name -> site.v1.ResumeSkill
	11, // 3: site.v1.Resume.projects:type_name -> site.v1.ResumeProject
	1,  // 4: site.v1.AdminService.Login:input_type -> site.v1.LoginRequest
	3,  // 5: site.v1.AdminService.SearchAnime:input_type -> site.v1.SearchRequest
	0,  // 6: site.v1.AdminService.ListTracked:input_type -> site.v1.Empty
	4,  // 7: site.v1.AdminService.TrackAnime:input_type -> site.v1.AnimeId
	4,  // 8: site.v1.AdminService.UntrackAnime:input_type -> site.v1.AnimeId
	0,  // 9: site.v1.AdminService.RunReleaseCheck:input_type -> site.v1.Empty
	0,  // 10: site.v1.AdminService.GetResume:input_type -> site.v1.Empty
	12, // 11: site.v1.AdminService.TailorResume:input_type -> site.v1.TailorRequest
	2,  // 12: site.v1.AdminService.Login:output_type -> site.v1.LoginReply
	7,  // 13: site.v1.AdminService.SearchAnime:output_type -> site.v1.AnimeList
	7,  // 14: site.v1.AdminService.ListTracked:output_type -> site.v1.AnimeList
	13, // 15: site.v1.AdminService.TrackAnime:output_type -> site.v1.Ack
	13, // 16: site.v1.AdminService.UntrackAnime:output_type -> site.v1.Ack
	5,  // 17: site.v1.AdminService.RunReleaseCheck:output_type -> site.v1.CheckReply
	8,  // 18: site.v1.AdminService.GetResume:output_type -> site.v1.Resume
	8,  // 19: site.v1.AdminService.TailorResume:output_type -> site.v1.Resume
	12, // [12:20] is the sub-list for method output_type
	4,  // [4:12] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_admin_proto_init() }
func file_admin_proto_init() {
	if File_admin_proto != nil {
		return
	}
	file_site_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_proto_rawDesc), len(file_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_proto_goTypes,
		DependencyIndexes: file_admin_proto_depIdxs,
		MessageInfos:      file_admin_proto_msgTypes,
	}.Build()
	File_admin_proto = out.File
	file_admin_proto_goTypes = nil
	file_admin_proto_depIdxs = nil
}
