// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: admin.proto

package sitepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminService_Login_FullMethodName           = "/site.v1.AdminService/Login"
	AdminService_SearchAnime_FullMethodName     = "/site.v1.AdminService/SearchAnime"
	AdminService_ListTracked_FullMethodName     = "/site.v1.AdminService/ListTracked"
	AdminService_TrackAnime_FullMethodName      = "/site.v1.AdminService/TrackAnime"
	AdminService_UntrackAnime_FullMethodName    = "/site.v1.AdminService/UntrackAnime"
	AdminService_RunReleaseCheck_FullMethodName = "/site.v1.AdminService/RunReleaseCheck"
	AdminService_GetResume_FullMethodName       = "/site.v1.AdminService/GetResume"
	AdminService_TailorResume_FullMethodName    = "/site.v1.AdminService/TailorResume"
	AdminService_GetSettings_FullMethodName     = "/site.v1.AdminService/GetSettings"
	AdminService_SaveSettings_FullMethodName    = "/site.v1.AdminService/SaveSettings"
	AdminService_ListModels_FullMethodName      = "/site.v1.AdminService/ListModels"
)

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AdminService is the owner-gated control plane — the anime tracker and the résumé tailoring tool.
// This is the data plane for the admin console (a GWC/WASM frontend talks to it over the same
// GoGRPCBridge WebSocket tunnel as the public site). Every method except Login requires a valid
// session token in the "authorization" request metadata (value: "Bearer <token>"); the server
// enforces this with a unary interceptor. Documents (the RSS feeds and the résumé PDF page) stay
// on the HTTP GET document plane and are not part of this service.
type AdminServiceClient interface {
	// Login exchanges the admin password for a signed session token used by every other method.
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error)
	// SearchAnime queries AniList and marks which results are already tracked.
	SearchAnime(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*AnimeList, error)
	// ListTracked returns the currently tracked shows.
	ListTracked(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AnimeList, error)
	// TrackAnime begins tracking an AniList id.
	TrackAnime(ctx context.Context, in *AnimeId, opts ...grpc.CallOption) (*Ack, error)
	// UntrackAnime stops tracking an AniList id.
	UntrackAnime(ctx context.Context, in *AnimeId, opts ...grpc.CallOption) (*Ack, error)
	// RunReleaseCheck refreshes tracked shows against AniList and reports how many changed.
	RunReleaseCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CheckReply, error)
	// GetResume returns the canonical résumé data (the source the tailor refines).
	GetResume(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Resume, error)
	// TailorResume fetches a job posting and returns a résumé re-emphasized to fit it. The result
	// is constrained to the canonical résumé — the model cannot fabricate employers/skills/etc.
	TailorResume(ctx context.Context, in *TailorRequest, opts ...grpc.CallOption) (*Resume, error)
	// GetSettings returns the current settings (the API key is never returned — only whether one is set).
	GetSettings(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Settings, error)
	// SaveSettings persists settings. A blank openai_api_key leaves the stored key unchanged.
	SaveSettings(ctx context.Context, in *Settings, opts ...grpc.CallOption) (*Ack, error)
	// ListModels returns the chat models available to the stored OpenAI key.
	ListModels(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ModelList, error)
}

type adminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminServiceClient(cc grpc.ClientConnInterface) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginReply)
	err := c.cc.Invoke(ctx, AdminService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) SearchAnime(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*AnimeList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnimeList)
	err := c.cc.Invoke(ctx, AdminService_SearchAnime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ListTracked(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AnimeList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnimeList)
	err := c.cc.Invoke(ctx, AdminService_ListTracked_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) TrackAnime(ctx context.Context, in *AnimeId, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, AdminService_TrackAnime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) UntrackAnime(ctx context.Context, in *AnimeId, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, AdminService_UntrackAnime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) RunReleaseCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CheckReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckReply)
	err := c.cc.Invoke(ctx, AdminService_RunReleaseCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetResume(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Resume, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Resume)
	err := c.cc.Invoke(ctx, AdminService_GetResume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) TailorResume(ctx context.Context, in *TailorRequest, opts ...grpc.CallOption) (*Resume, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Resume)
	err := c.cc.Invoke(ctx, AdminService_TailorResume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetSettings(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Settings, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Settings)
	err := c.cc.Invoke(ctx, AdminService_GetSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) SaveSettings(ctx context.Context, in *Settings, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, AdminService_SaveSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ListModels(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ModelList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelList)
	err := c.cc.Invoke(ctx, AdminService_ListModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServiceServer is the server API for AdminService service.
// All implementations must embed UnimplementedAdminServiceServer
// for forward compatibility.
//
// AdminService is the owner-gated control plane — the anime tracker and the résumé tailoring tool.
// This is the data plane for the admin console (a GWC/WASM frontend talks to it over the same
// GoGRPCBridge WebSocket tunnel as the public site). Every method except Login requires a valid
// session token in the "authorization" request metadata (value: "Bearer <token>"); the server
// enforces this with a unary interceptor. Documents (the RSS feeds and the résumé PDF page) stay
// on the HTTP GET document plane and are not part of this service.
type AdminServiceServer interface {
	// Login exchanges the admin password for a signed session token used by every other method.
	Login(context.Context, *LoginRequest) (*LoginReply, error)
	// SearchAnime queries AniList and marks which results are already tracked.
	SearchAnime(context.Context, *SearchRequest) (*AnimeList, error)
	// ListTracked returns the currently tracked shows.
	ListTracked(context.Context, *Empty) (*AnimeList, error)
	// TrackAnime begins tracking an AniList id.
	TrackAnime(context.Context, *AnimeId) (*Ack, error)
	// UntrackAnime stops tracking an AniList id.
	UntrackAnime(context.Context, *AnimeId) (*Ack, error)
	// RunReleaseCheck refreshes tracked shows against AniList and reports how many changed.
	RunReleaseCheck(context.Context, *Empty) (*CheckReply, error)
	// GetResume returns the canonical résumé data (the source the tailor refines).
	GetResume(context.Context, *Empty) (*Resume, error)
	// TailorResume fetches a job posting and returns a résumé re-emphasized to fit it. The result
	// is constrained to the canonical résumé — the model cannot fabricate employers/skills/etc.
	TailorResume(context.Context, *TailorRequest) (*Resume, error)
	// GetSettings returns the current settings (the API key is never returned — only whether one is set).
	GetSettings(context.Context, *Empty) (*Settings, error)
	// SaveSettings persists settings. A blank openai_api_key leaves the stored key unchanged.
	SaveSettings(context.Context, *Settings) (*Ack, error)
	// ListModels returns the chat models available to the stored OpenAI key.
	ListModels(context.Context, *Empty) (*ModelList, error)
	mustEmbedUnimplementedAdminServiceServer()
}

// UnimplementedAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminServiceServer struct{}

func (UnimplementedAdminServiceServer) Login(context.Context, *LoginRequest) (*LoginReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedAdminServiceServer) SearchAnime(context.Context, *SearchRequest) (*AnimeList, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchAnime not implemented")
}
func (UnimplementedAdminServiceServer) ListTracked(context.Context, *Empty) (*AnimeList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTracked not implemented")
}
func (UnimplementedAdminServiceServer) TrackAnime(context.Context, *AnimeId) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method TrackAnime not implemented")
}
func (UnimplementedAdminServiceServer) UntrackAnime(context.Context, *AnimeId) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method UntrackAnime not implemented")
}
func (UnimplementedAdminServiceServer) RunReleaseCheck(context.Context, *Empty) (*CheckReply, error) {
	return nil, status.Error(codes.Unimplemented, "method RunReleaseCheck not implemented")
}
func (UnimplementedAdminServiceServer) GetResume(context.Context, *Empty) (*Resume, error) {
	return nil, status.Error(codes.Unimplemented, "method GetResume not implemented")
}
func (UnimplementedAdminServiceServer) TailorResume(context.Context, *TailorRequest) (*Resume, error) {
	return nil, status.Error(codes.Unimplemented, "method TailorResume not implemented")
}
func (UnimplementedAdminServiceServer) GetSettings(context.Context, *Empty) (*Settings, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSettings not implemented")
}
func (UnimplementedAdminServiceServer) SaveSettings(context.Context, *Settings) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveSettings not implemented")
}
func (UnimplementedAdminServiceServer) ListModels(context.Context, *Empty) (*ModelList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListModels not implemented")
}
func (UnimplementedAdminServiceServer) mustEmbedUnimplementedAdminServiceServer() {}
func (UnimplementedAdminServiceServer) testEmbeddedByValue()                      {}

// UnsafeAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServiceServer will
// result in compilation errors.
type UnsafeAdminServiceServer interface {
	mustEmbedUnimplementedAdminServiceServer()
}

func RegisterAdminServiceServer(s grpc.ServiceRegistrar, srv AdminServiceServer) {
	// If the following call panics, it indicates UnimplementedAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminService_ServiceDesc, srv)
}

func _AdminService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_SearchAnime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).SearchAnime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_SearchAnime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).SearchAnime(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ListTracked_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ListTracked(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ListTracked_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ListTracked(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_TrackAnime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnimeId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).TrackAnime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_TrackAnime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).TrackAnime(ctx, req.(*AnimeId))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_UntrackAnime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnimeId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).UntrackAnime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_UntrackAnime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).UntrackAnime(ctx, req.(*AnimeId))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_RunReleaseCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).RunReleaseCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_RunReleaseCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).RunReleaseCheck(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetResume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetResume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetResume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetResume(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_TailorResume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TailorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).TailorResume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_TailorResume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).TailorResume(ctx, req.(*TailorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetSettings(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_SaveSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Settings)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).SaveSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_SaveSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).SaveSettings(ctx, req.(*Settings))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ListModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ListModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ListModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ListModels(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminService_ServiceDesc is the grpc.ServiceDesc for AdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "site.v1.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _AdminService_Login_Handler,
		},
		{
			MethodName: "SearchAnime",
			Handler:    _AdminService_SearchAnime_Handler,
		},
		{
			MethodName: "ListTracked",
			Handler:    _AdminService_ListTracked_Handler,
		},
		{
			MethodName: "TrackAnime",
			Handler:    _AdminService_TrackAnime_Handler,
		},
		{
			MethodName: "UntrackAnime",
			Handler:    _AdminService_UntrackAnime_Handler,
		},
		{
			MethodName: "RunReleaseCheck",
			Handler:    _AdminService_RunReleaseCheck_Handler,
		},
		{
			MethodName: "GetResume",
			Handler:    _AdminService_GetResume_Handler,
		},
		{
			MethodName: "TailorResume",
			Handler:    _AdminService_TailorResume_Handler,
		},
		{
			MethodName: "GetSettings",
			Handler:    _AdminService_GetSettings_Handler,
		},
		{
			MethodName: "SaveSettings",
			Handler:    _AdminService_SaveSettings_Handler,
		},
		{
			MethodName: "ListModels",
			Handler:    _AdminService_ListModels_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin.proto",
}
