// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: admin.proto

package sitepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminService_Login_FullMethodName                      = "/site.v1.AdminService/Login"
	AdminService_AuthState_FullMethodName                  = "/site.v1.AdminService/AuthState"
	AdminService_Setup_FullMethodName                      = "/site.v1.AdminService/Setup"
	AdminService_ResetPassword_FullMethodName              = "/site.v1.AdminService/ResetPassword"
	AdminService_SearchAnime_FullMethodName                = "/site.v1.AdminService/SearchAnime"
	AdminService_ListTracked_FullMethodName                = "/site.v1.AdminService/ListTracked"
	AdminService_TrackAnime_FullMethodName                 = "/site.v1.AdminService/TrackAnime"
	AdminService_UntrackAnime_FullMethodName               = "/site.v1.AdminService/UntrackAnime"
	AdminService_RunReleaseCheck_FullMethodName            = "/site.v1.AdminService/RunReleaseCheck"
	AdminService_GetResume_FullMethodName                  = "/site.v1.AdminService/GetResume"
	AdminService_ApplyResume_FullMethodName                = "/site.v1.AdminService/ApplyResume"
	AdminService_TailorResume_FullMethodName               = "/site.v1.AdminService/TailorResume"
	AdminService_GetSettings_FullMethodName                = "/site.v1.AdminService/GetSettings"
	AdminService_SaveSettings_FullMethodName               = "/site.v1.AdminService/SaveSettings"
	AdminService_ListModels_FullMethodName                 = "/site.v1.AdminService/ListModels"
	AdminService_GetLastTailoring_FullMethodName           = "/site.v1.AdminService/GetLastTailoring"
	AdminService_GetBaseResume_FullMethodName              = "/site.v1.AdminService/GetBaseResume"
	AdminService_ListTailorings_FullMethodName             = "/site.v1.AdminService/ListTailorings"
	AdminService_GetTailoring_FullMethodName               = "/site.v1.AdminService/GetTailoring"
	AdminService_DeleteTailoring_FullMethodName            = "/site.v1.AdminService/DeleteTailoring"
	AdminService_GetPrompt_FullMethodName                  = "/site.v1.AdminService/GetPrompt"
	AdminService_SavePrompt_FullMethodName                 = "/site.v1.AdminService/SavePrompt"
	AdminService_DryRunPrompt_FullMethodName               = "/site.v1.AdminService/DryRunPrompt"
	AdminService_GetSlackConfig_FullMethodName             = "/site.v1.AdminService/GetSlackConfig"
	AdminService_SaveSlackConfig_FullMethodName            = "/site.v1.AdminService/SaveSlackConfig"
	AdminService_PostToSlackNow_FullMethodName             = "/site.v1.AdminService/PostToSlackNow"
	AdminService_MintCashFluxActivationCode_FullMethodName = "/site.v1.AdminService/MintCashFluxActivationCode"
	AdminService_ListCashFluxPendingDevices_FullMethodName = "/site.v1.AdminService/ListCashFluxPendingDevices"
	AdminService_ApproveCashFluxPairing_FullMethodName     = "/site.v1.AdminService/ApproveCashFluxPairing"
	AdminService_RejectCashFluxPairing_FullMethodName      = "/site.v1.AdminService/RejectCashFluxPairing"
	AdminService_ListCashFluxUsers_FullMethodName          = "/site.v1.AdminService/ListCashFluxUsers"
	AdminService_GetCashFluxStorageStats_FullMethodName    = "/site.v1.AdminService/GetCashFluxStorageStats"
	AdminService_DeleteCashFluxUser_FullMethodName         = "/site.v1.AdminService/DeleteCashFluxUser"
)

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AdminService is the owner-gated control plane — the anime tracker and the résumé tailoring tool.
// This is the data plane for the admin console (a GWC/WASM frontend talks to it over the same
// GoGRPCBridge WebSocket tunnel as the public site). Every method except Login requires a valid
// session token in the "authorization" request metadata (value: "Bearer <token>"); the server
// enforces this with a unary interceptor. Documents (the RSS feeds and the résumé PDF page) stay
// on the HTTP GET document plane and are not part of this service.
type AdminServiceClient interface {
	// Login exchanges the admin password for a signed session token used by every other method.
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error)
	// AuthState reports whether the deployed site still needs first-run owner setup, and the recovery
	// hint to show on the reset screen. Public (no session): the client calls it before login.
	AuthState(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AuthStateReply, error)
	// Setup creates the owner account on first run and returns the one-time recovery phrase. Public,
	// but the server refuses once an account exists or when env credentials manage auth.
	Setup(ctx context.Context, in *SetupRequest, opts ...grpc.CallOption) (*SetupReply, error)
	// ResetPassword verifies the recovery phrase (or the env break-glass) and sets a new password,
	// returning the rotated recovery phrase. Public (the owner is locked out by definition).
	ResetPassword(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*ResetReply, error)
	// SearchAnime queries AniList and marks which results are already tracked.
	SearchAnime(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*AnimeList, error)
	// ListTracked returns the currently tracked shows.
	ListTracked(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AnimeList, error)
	// TrackAnime begins tracking an AniList id.
	TrackAnime(ctx context.Context, in *AnimeId, opts ...grpc.CallOption) (*Ack, error)
	// UntrackAnime stops tracking an AniList id.
	UntrackAnime(ctx context.Context, in *AnimeId, opts ...grpc.CallOption) (*Ack, error)
	// RunReleaseCheck refreshes tracked shows against AniList and reports how many changed.
	RunReleaseCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CheckReply, error)
	// GetResume returns the active résumé — the applied override if one exists, else the canonical.
	GetResume(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Resume, error)
	// ApplyResume saves a résumé as the active one (served by GetResume and the /resume page).
	ApplyResume(ctx context.Context, in *Resume, opts ...grpc.CallOption) (*Ack, error)
	// TailorResume fetches a job posting and returns the tailored résumé plus the signals extracted
	// from the posting and the rationale for each tailoring choice. The résumé is constrained to the
	// canonical one — the model cannot fabricate employers/skills/etc.
	TailorResume(ctx context.Context, in *TailorRequest, opts ...grpc.CallOption) (*TailorResult, error)
	// GetSettings returns the current settings (the API key is never returned — only whether one is set).
	GetSettings(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Settings, error)
	// SaveSettings persists settings. A blank openai_api_key leaves the stored key unchanged.
	SaveSettings(ctx context.Context, in *Settings, opts ...grpc.CallOption) (*Ack, error)
	// ListModels returns the chat models available to the stored OpenAI key.
	ListModels(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ModelList, error)
	// GetLastTailoring returns the most recent saved tailoring result (empty resume if none).
	GetLastTailoring(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TailorResult, error)
	// GetBaseResume returns the permanent canonical résumé (the diff baseline; never overwritten).
	GetBaseResume(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Resume, error)
	// ListTailorings returns saved tailoring variants (metadata only), newest first.
	ListTailorings(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TailoringList, error)
	// GetTailoring loads one saved variant's full result by id (for re-opening / re-tweaking).
	GetTailoring(ctx context.Context, in *TailoringId, opts ...grpc.CallOption) (*TailorResult, error)
	// DeleteTailoring removes a saved variant by id.
	DeleteTailoring(ctx context.Context, in *TailoringId, opts ...grpc.CallOption) (*Ack, error)
	// --- RSS / anime control panel ---
	// GetPrompt returns the single QOTD generation instruction (the default when none is saved).
	GetPrompt(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PromptText, error)
	// SavePrompt stores the single QOTD generation instruction.
	SavePrompt(ctx context.Context, in *PromptText, opts ...grpc.CallOption) (*Ack, error)
	// DryRunPrompt generates a preview anime discussion post from the given prompt (fetching the latest
	// anime news) WITHOUT publishing it — for testing the prompt.
	DryRunPrompt(ctx context.Context, in *PromptText, opts ...grpc.CallOption) (*PostPreview, error)
	// GetSlackConfig returns the Slack posting config (the webhook URL is never returned, only whether set).
	GetSlackConfig(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SlackConfig, error)
	// SaveSlackConfig persists the Slack config (a blank webhook_url leaves the stored one unchanged).
	SaveSlackConfig(ctx context.Context, in *SlackConfig, opts ...grpc.CallOption) (*Ack, error)
	// PostToSlackNow generates a post from the saved prompt, posts it to Slack, and publishes it to the
	// QOTD RSS feed.
	PostToSlackNow(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Ack, error)
	// --- CashFlux device pairing (embedded admin-approved bootstrap) ---
	// MintCashFluxActivationCode mints a short-lived, single-use activation code bound to this
	// deployment's single CashFlux owner account (created on the first call). Typed into any CashFlux
	// client's Settings -> Cloud, it turns that device into a signed-in one — no pending request to
	// approve first, and every code lands in the SAME account so all activated devices sync together.
	// Being able to mint one is the whole access control: it requires an admin session on this site.
	// Fails FailedPrecondition when CashFlux embedding isn't configured on this deployment.
	MintCashFluxActivationCode(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CashFluxActivationCode, error)
	// ListCashFluxPendingDevices returns every unresolved device-pairing request, oldest first. Fails
	// FailedPrecondition when CashFlux embedding isn't configured on this deployment.
	ListCashFluxPendingDevices(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CashFluxPendingDeviceList, error)
	// ApproveCashFluxPairing approves a pending device request, creating a brand-new CashFlux account
	// for it and returning the pairing code so the admin can read it to (or cross-check it against) the
	// person on the device. approved is false (with no pairing_code) when the request was already
	// resolved or expired — that is not an error.
	ApproveCashFluxPairing(ctx context.Context, in *CashFluxApprovePairingRequest, opts ...grpc.CallOption) (*CashFluxApprovePairingResponse, error)
	// RejectCashFluxPairing declines a pending device request. rejected is false when the request was
	// already resolved or expired — that is not an error.
	RejectCashFluxPairing(ctx context.Context, in *CashFluxRejectPairingRequest, opts ...grpc.CallOption) (*CashFluxRejectPairingResponse, error)
	// ListCashFluxUsers returns a page of enrolled CashFlux accounts, newest first, each carrying its
	// current calendar month's request volume. Fails FailedPrecondition when CashFlux embedding isn't
	// configured on this deployment.
	ListCashFluxUsers(ctx context.Context, in *CashFluxListUsersRequest, opts ...grpc.CallOption) (*CashFluxUserList, error)
	// GetCashFluxStorageStats reports the embedded CashFlux database's on-disk size and the total size
	// of every stored artifact blob. Fails FailedPrecondition when CashFlux embedding isn't configured
	// on this deployment.
	GetCashFluxStorageStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CashFluxStorageStats, error)
	// DeleteCashFluxUser permanently purges an enrolled account and everything it owns —
	// workspaces, dataset snapshots, artifact blobs, AI keys, and every refresh token, so the
	// account cannot be resurrected by a session that outlived it. deleted is false (with no
	// error) when no such account exists, which is what a double-submit or a stale listing
	// looks like. Not reversible. Fails FailedPrecondition when CashFlux embedding isn't
	// configured on this deployment.
	DeleteCashFluxUser(ctx context.Context, in *CashFluxDeleteUserRequest, opts ...grpc.CallOption) (*CashFluxDeleteUserResponse, error)
}

type adminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminServiceClient(cc grpc.ClientConnInterface) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginReply)
	err := c.cc.Invoke(ctx, AdminService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) AuthState(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AuthStateReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthStateReply)
	err := c.cc.Invoke(ctx, AdminService_AuthState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) Setup(ctx context.Context, in *SetupRequest, opts ...grpc.CallOption) (*SetupReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetupReply)
	err := c.cc.Invoke(ctx, AdminService_Setup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ResetPassword(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*ResetReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResetReply)
	err := c.cc.Invoke(ctx, AdminService_ResetPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) SearchAnime(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*AnimeList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnimeList)
	err := c.cc.Invoke(ctx, AdminService_SearchAnime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ListTracked(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AnimeList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnimeList)
	err := c.cc.Invoke(ctx, AdminService_ListTracked_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) TrackAnime(ctx context.Context, in *AnimeId, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, AdminService_TrackAnime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) UntrackAnime(ctx context.Context, in *AnimeId, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, AdminService_UntrackAnime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) RunReleaseCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CheckReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckReply)
	err := c.cc.Invoke(ctx, AdminService_RunReleaseCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetResume(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Resume, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Resume)
	err := c.cc.Invoke(ctx, AdminService_GetResume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ApplyResume(ctx context.Context, in *Resume, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, AdminService_ApplyResume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) TailorResume(ctx context.Context, in *TailorRequest, opts ...grpc.CallOption) (*TailorResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TailorResult)
	err := c.cc.Invoke(ctx, AdminService_TailorResume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetSettings(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Settings, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Settings)
	err := c.cc.Invoke(ctx, AdminService_GetSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) SaveSettings(ctx context.Context, in *Settings, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, AdminService_SaveSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ListModels(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ModelList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelList)
	err := c.cc.Invoke(ctx, AdminService_ListModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetLastTailoring(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TailorResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TailorResult)
	err := c.cc.Invoke(ctx, AdminService_GetLastTailoring_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetBaseResume(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Resume, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Resume)
	err := c.cc.Invoke(ctx, AdminService_GetBaseResume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ListTailorings(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TailoringList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TailoringList)
	err := c.cc.Invoke(ctx, AdminService_ListTailorings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetTailoring(ctx context.Context, in *TailoringId, opts ...grpc.CallOption) (*TailorResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TailorResult)
	err := c.cc.Invoke(ctx, AdminService_GetTailoring_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) DeleteTailoring(ctx context.Context, in *TailoringId, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, AdminService_DeleteTailoring_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetPrompt(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PromptText, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PromptText)
	err := c.cc.Invoke(ctx, AdminService_GetPrompt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) SavePrompt(ctx context.Context, in *PromptText, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, AdminService_SavePrompt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) DryRunPrompt(ctx context.Context, in *PromptText, opts ...grpc.CallOption) (*PostPreview, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostPreview)
	err := c.cc.Invoke(ctx, AdminService_DryRunPrompt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetSlackConfig(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SlackConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SlackConfig)
	err := c.cc.Invoke(ctx, AdminService_GetSlackConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) SaveSlackConfig(ctx context.Context, in *SlackConfig, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, AdminService_SaveSlackConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) PostToSlackNow(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, AdminService_PostToSlackNow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) MintCashFluxActivationCode(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CashFluxActivationCode, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CashFluxActivationCode)
	err := c.cc.Invoke(ctx, AdminService_MintCashFluxActivationCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ListCashFluxPendingDevices(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CashFluxPendingDeviceList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CashFluxPendingDeviceList)
	err := c.cc.Invoke(ctx, AdminService_ListCashFluxPendingDevices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ApproveCashFluxPairing(ctx context.Context, in *CashFluxApprovePairingRequest, opts ...grpc.CallOption) (*CashFluxApprovePairingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CashFluxApprovePairingResponse)
	err := c.cc.Invoke(ctx, AdminService_ApproveCashFluxPairing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) RejectCashFluxPairing(ctx context.Context, in *CashFluxRejectPairingRequest, opts ...grpc.CallOption) (*CashFluxRejectPairingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CashFluxRejectPairingResponse)
	err := c.cc.Invoke(ctx, AdminService_RejectCashFluxPairing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ListCashFluxUsers(ctx context.Context, in *CashFluxListUsersRequest, opts ...grpc.CallOption) (*CashFluxUserList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CashFluxUserList)
	err := c.cc.Invoke(ctx, AdminService_ListCashFluxUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetCashFluxStorageStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CashFluxStorageStats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CashFluxStorageStats)
	err := c.cc.Invoke(ctx, AdminService_GetCashFluxStorageStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) DeleteCashFluxUser(ctx context.Context, in *CashFluxDeleteUserRequest, opts ...grpc.CallOption) (*CashFluxDeleteUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CashFluxDeleteUserResponse)
	err := c.cc.Invoke(ctx, AdminService_DeleteCashFluxUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServiceServer is the server API for AdminService service.
// All implementations must embed UnimplementedAdminServiceServer
// for forward compatibility.
//
// AdminService is the owner-gated control plane — the anime tracker and the résumé tailoring tool.
// This is the data plane for the admin console (a GWC/WASM frontend talks to it over the same
// GoGRPCBridge WebSocket tunnel as the public site). Every method except Login requires a valid
// session token in the "authorization" request metadata (value: "Bearer <token>"); the server
// enforces this with a unary interceptor. Documents (the RSS feeds and the résumé PDF page) stay
// on the HTTP GET document plane and are not part of this service.
type AdminServiceServer interface {
	// Login exchanges the admin password for a signed session token used by every other method.
	Login(context.Context, *LoginRequest) (*LoginReply, error)
	// AuthState reports whether the deployed site still needs first-run owner setup, and the recovery
	// hint to show on the reset screen. Public (no session): the client calls it before login.
	AuthState(context.Context, *Empty) (*AuthStateReply, error)
	// Setup creates the owner account on first run and returns the one-time recovery phrase. Public,
	// but the server refuses once an account exists or when env credentials manage auth.
	Setup(context.Context, *SetupRequest) (*SetupReply, error)
	// ResetPassword verifies the recovery phrase (or the env break-glass) and sets a new password,
	// returning the rotated recovery phrase. Public (the owner is locked out by definition).
	ResetPassword(context.Context, *ResetRequest) (*ResetReply, error)
	// SearchAnime queries AniList and marks which results are already tracked.
	SearchAnime(context.Context, *SearchRequest) (*AnimeList, error)
	// ListTracked returns the currently tracked shows.
	ListTracked(context.Context, *Empty) (*AnimeList, error)
	// TrackAnime begins tracking an AniList id.
	TrackAnime(context.Context, *AnimeId) (*Ack, error)
	// UntrackAnime stops tracking an AniList id.
	UntrackAnime(context.Context, *AnimeId) (*Ack, error)
	// RunReleaseCheck refreshes tracked shows against AniList and reports how many changed.
	RunReleaseCheck(context.Context, *Empty) (*CheckReply, error)
	// GetResume returns the active résumé — the applied override if one exists, else the canonical.
	GetResume(context.Context, *Empty) (*Resume, error)
	// ApplyResume saves a résumé as the active one (served by GetResume and the /resume page).
	ApplyResume(context.Context, *Resume) (*Ack, error)
	// TailorResume fetches a job posting and returns the tailored résumé plus the signals extracted
	// from the posting and the rationale for each tailoring choice. The résumé is constrained to the
	// canonical one — the model cannot fabricate employers/skills/etc.
	TailorResume(context.Context, *TailorRequest) (*TailorResult, error)
	// GetSettings returns the current settings (the API key is never returned — only whether one is set).
	GetSettings(context.Context, *Empty) (*Settings, error)
	// SaveSettings persists settings. A blank openai_api_key leaves the stored key unchanged.
	SaveSettings(context.Context, *Settings) (*Ack, error)
	// ListModels returns the chat models available to the stored OpenAI key.
	ListModels(context.Context, *Empty) (*ModelList, error)
	// GetLastTailoring returns the most recent saved tailoring result (empty resume if none).
	GetLastTailoring(context.Context, *Empty) (*TailorResult, error)
	// GetBaseResume returns the permanent canonical résumé (the diff baseline; never overwritten).
	GetBaseResume(context.Context, *Empty) (*Resume, error)
	// ListTailorings returns saved tailoring variants (metadata only), newest first.
	ListTailorings(context.Context, *Empty) (*TailoringList, error)
	// GetTailoring loads one saved variant's full result by id (for re-opening / re-tweaking).
	GetTailoring(context.Context, *TailoringId) (*TailorResult, error)
	// DeleteTailoring removes a saved variant by id.
	DeleteTailoring(context.Context, *TailoringId) (*Ack, error)
	// --- RSS / anime control panel ---
	// GetPrompt returns the single QOTD generation instruction (the default when none is saved).
	GetPrompt(context.Context, *Empty) (*PromptText, error)
	// SavePrompt stores the single QOTD generation instruction.
	SavePrompt(context.Context, *PromptText) (*Ack, error)
	// DryRunPrompt generates a preview anime discussion post from the given prompt (fetching the latest
	// anime news) WITHOUT publishing it — for testing the prompt.
	DryRunPrompt(context.Context, *PromptText) (*PostPreview, error)
	// GetSlackConfig returns the Slack posting config (the webhook URL is never returned, only whether set).
	GetSlackConfig(context.Context, *Empty) (*SlackConfig, error)
	// SaveSlackConfig persists the Slack config (a blank webhook_url leaves the stored one unchanged).
	SaveSlackConfig(context.Context, *SlackConfig) (*Ack, error)
	// PostToSlackNow generates a post from the saved prompt, posts it to Slack, and publishes it to the
	// QOTD RSS feed.
	PostToSlackNow(context.Context, *Empty) (*Ack, error)
	// --- CashFlux device pairing (embedded admin-approved bootstrap) ---
	// MintCashFluxActivationCode mints a short-lived, single-use activation code bound to this
	// deployment's single CashFlux owner account (created on the first call). Typed into any CashFlux
	// client's Settings -> Cloud, it turns that device into a signed-in one — no pending request to
	// approve first, and every code lands in the SAME account so all activated devices sync together.
	// Being able to mint one is the whole access control: it requires an admin session on this site.
	// Fails FailedPrecondition when CashFlux embedding isn't configured on this deployment.
	MintCashFluxActivationCode(context.Context, *Empty) (*CashFluxActivationCode, error)
	// ListCashFluxPendingDevices returns every unresolved device-pairing request, oldest first. Fails
	// FailedPrecondition when CashFlux embedding isn't configured on this deployment.
	ListCashFluxPendingDevices(context.Context, *Empty) (*CashFluxPendingDeviceList, error)
	// ApproveCashFluxPairing approves a pending device request, creating a brand-new CashFlux account
	// for it and returning the pairing code so the admin can read it to (or cross-check it against) the
	// person on the device. approved is false (with no pairing_code) when the request was already
	// resolved or expired — that is not an error.
	ApproveCashFluxPairing(context.Context, *CashFluxApprovePairingRequest) (*CashFluxApprovePairingResponse, error)
	// RejectCashFluxPairing declines a pending device request. rejected is false when the request was
	// already resolved or expired — that is not an error.
	RejectCashFluxPairing(context.Context, *CashFluxRejectPairingRequest) (*CashFluxRejectPairingResponse, error)
	// ListCashFluxUsers returns a page of enrolled CashFlux accounts, newest first, each carrying its
	// current calendar month's request volume. Fails FailedPrecondition when CashFlux embedding isn't
	// configured on this deployment.
	ListCashFluxUsers(context.Context, *CashFluxListUsersRequest) (*CashFluxUserList, error)
	// GetCashFluxStorageStats reports the embedded CashFlux database's on-disk size and the total size
	// of every stored artifact blob. Fails FailedPrecondition when CashFlux embedding isn't configured
	// on this deployment.
	GetCashFluxStorageStats(context.Context, *Empty) (*CashFluxStorageStats, error)
	// DeleteCashFluxUser permanently purges an enrolled account and everything it owns —
	// workspaces, dataset snapshots, artifact blobs, AI keys, and every refresh token, so the
	// account cannot be resurrected by a session that outlived it. deleted is false (with no
	// error) when no such account exists, which is what a double-submit or a stale listing
	// looks like. Not reversible. Fails FailedPrecondition when CashFlux embedding isn't
	// configured on this deployment.
	DeleteCashFluxUser(context.Context, *CashFluxDeleteUserRequest) (*CashFluxDeleteUserResponse, error)
	mustEmbedUnimplementedAdminServiceServer()
}

// UnimplementedAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminServiceServer struct{}

func (UnimplementedAdminServiceServer) Login(context.Context, *LoginRequest) (*LoginReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedAdminServiceServer) AuthState(context.Context, *Empty) (*AuthStateReply, error) {
	return nil, status.Error(codes.Unimplemented, "method AuthState not implemented")
}
func (UnimplementedAdminServiceServer) Setup(context.Context, *SetupRequest) (*SetupReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Setup not implemented")
}
func (UnimplementedAdminServiceServer) ResetPassword(context.Context, *ResetRequest) (*ResetReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ResetPassword not implemented")
}
func (UnimplementedAdminServiceServer) SearchAnime(context.Context, *SearchRequest) (*AnimeList, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchAnime not implemented")
}
func (UnimplementedAdminServiceServer) ListTracked(context.Context, *Empty) (*AnimeList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTracked not implemented")
}
func (UnimplementedAdminServiceServer) TrackAnime(context.Context, *AnimeId) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method TrackAnime not implemented")
}
func (UnimplementedAdminServiceServer) UntrackAnime(context.Context, *AnimeId) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method UntrackAnime not implemented")
}
func (UnimplementedAdminServiceServer) RunReleaseCheck(context.Context, *Empty) (*CheckReply, error) {
	return nil, status.Error(codes.Unimplemented, "method RunReleaseCheck not implemented")
}
func (UnimplementedAdminServiceServer) GetResume(context.Context, *Empty) (*Resume, error) {
	return nil, status.Error(codes.Unimplemented, "method GetResume not implemented")
}
func (UnimplementedAdminServiceServer) ApplyResume(context.Context, *Resume) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyResume not implemented")
}
func (UnimplementedAdminServiceServer) TailorResume(context.Context, *TailorRequest) (*TailorResult, error) {
	return nil, status.Error(codes.Unimplemented, "method TailorResume not implemented")
}
func (UnimplementedAdminServiceServer) GetSettings(context.Context, *Empty) (*Settings, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSettings not implemented")
}
func (UnimplementedAdminServiceServer) SaveSettings(context.Context, *Settings) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveSettings not implemented")
}
func (UnimplementedAdminServiceServer) ListModels(context.Context, *Empty) (*ModelList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListModels not implemented")
}
func (UnimplementedAdminServiceServer) GetLastTailoring(context.Context, *Empty) (*TailorResult, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLastTailoring not implemented")
}
func (UnimplementedAdminServiceServer) GetBaseResume(context.Context, *Empty) (*Resume, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBaseResume not implemented")
}
func (UnimplementedAdminServiceServer) ListTailorings(context.Context, *Empty) (*TailoringList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTailorings not implemented")
}
func (UnimplementedAdminServiceServer) GetTailoring(context.Context, *TailoringId) (*TailorResult, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTailoring not implemented")
}
func (UnimplementedAdminServiceServer) DeleteTailoring(context.Context, *TailoringId) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTailoring not implemented")
}
func (UnimplementedAdminServiceServer) GetPrompt(context.Context, *Empty) (*PromptText, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPrompt not implemented")
}
func (UnimplementedAdminServiceServer) SavePrompt(context.Context, *PromptText) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method SavePrompt not implemented")
}
func (UnimplementedAdminServiceServer) DryRunPrompt(context.Context, *PromptText) (*PostPreview, error) {
	return nil, status.Error(codes.Unimplemented, "method DryRunPrompt not implemented")
}
func (UnimplementedAdminServiceServer) GetSlackConfig(context.Context, *Empty) (*SlackConfig, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSlackConfig not implemented")
}
func (UnimplementedAdminServiceServer) SaveSlackConfig(context.Context, *SlackConfig) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveSlackConfig not implemented")
}
func (UnimplementedAdminServiceServer) PostToSlackNow(context.Context, *Empty) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method PostToSlackNow not implemented")
}
func (UnimplementedAdminServiceServer) MintCashFluxActivationCode(context.Context, *Empty) (*CashFluxActivationCode, error) {
	return nil, status.Error(codes.Unimplemented, "method MintCashFluxActivationCode not implemented")
}
func (UnimplementedAdminServiceServer) ListCashFluxPendingDevices(context.Context, *Empty) (*CashFluxPendingDeviceList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCashFluxPendingDevices not implemented")
}
func (UnimplementedAdminServiceServer) ApproveCashFluxPairing(context.Context, *CashFluxApprovePairingRequest) (*CashFluxApprovePairingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApproveCashFluxPairing not implemented")
}
func (UnimplementedAdminServiceServer) RejectCashFluxPairing(context.Context, *CashFluxRejectPairingRequest) (*CashFluxRejectPairingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RejectCashFluxPairing not implemented")
}
func (UnimplementedAdminServiceServer) ListCashFluxUsers(context.Context, *CashFluxListUsersRequest) (*CashFluxUserList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCashFluxUsers not implemented")
}
func (UnimplementedAdminServiceServer) GetCashFluxStorageStats(context.Context, *Empty) (*CashFluxStorageStats, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCashFluxStorageStats not implemented")
}
func (UnimplementedAdminServiceServer) DeleteCashFluxUser(context.Context, *CashFluxDeleteUserRequest) (*CashFluxDeleteUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCashFluxUser not implemented")
}
func (UnimplementedAdminServiceServer) mustEmbedUnimplementedAdminServiceServer() {}
func (UnimplementedAdminServiceServer) testEmbeddedByValue()                      {}

// UnsafeAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServiceServer will
// result in compilation errors.
type UnsafeAdminServiceServer interface {
	mustEmbedUnimplementedAdminServiceServer()
}

func RegisterAdminServiceServer(s grpc.ServiceRegistrar, srv AdminServiceServer) {
	// If the following call panics, it indicates UnimplementedAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminService_ServiceDesc, srv)
}

func _AdminService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_AuthState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).AuthState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_AuthState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).AuthState(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_Setup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).Setup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_Setup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).Setup(ctx, req.(*SetupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ResetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ResetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ResetPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ResetPassword(ctx, req.(*ResetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_SearchAnime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).SearchAnime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_SearchAnime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).SearchAnime(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ListTracked_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ListTracked(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ListTracked_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ListTracked(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_TrackAnime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnimeId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).TrackAnime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_TrackAnime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).TrackAnime(ctx, req.(*AnimeId))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_UntrackAnime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnimeId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).UntrackAnime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_UntrackAnime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).UntrackAnime(ctx, req.(*AnimeId))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_RunReleaseCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).RunReleaseCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_RunReleaseCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).RunReleaseCheck(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetResume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetResume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetResume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetResume(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ApplyResume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Resume)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ApplyResume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ApplyResume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ApplyResume(ctx, req.(*Resume))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_TailorResume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TailorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).TailorResume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_TailorResume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).TailorResume(ctx, req.(*TailorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetSettings(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_SaveSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Settings)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).SaveSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_SaveSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).SaveSettings(ctx, req.(*Settings))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ListModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ListModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ListModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ListModels(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetLastTailoring_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetLastTailoring(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetLastTailoring_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetLastTailoring(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetBaseResume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetBaseResume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetBaseResume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetBaseResume(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ListTailorings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ListTailorings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ListTailorings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ListTailorings(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetTailoring_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TailoringId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetTailoring(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetTailoring_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetTailoring(ctx, req.(*TailoringId))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_DeleteTailoring_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TailoringId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).DeleteTailoring(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_DeleteTailoring_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).DeleteTailoring(ctx, req.(*TailoringId))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetPrompt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetPrompt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetPrompt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetPrompt(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_SavePrompt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromptText)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).SavePrompt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_SavePrompt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).SavePrompt(ctx, req.(*PromptText))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_DryRunPrompt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromptText)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).DryRunPrompt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_DryRunPrompt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).DryRunPrompt(ctx, req.(*PromptText))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetSlackConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetSlackConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetSlackConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetSlackConfig(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_SaveSlackConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SlackConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).SaveSlackConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_SaveSlackConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).SaveSlackConfig(ctx, req.(*SlackConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_PostToSlackNow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).PostToSlackNow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_PostToSlackNow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).PostToSlackNow(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_MintCashFluxActivationCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).MintCashFluxActivationCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_MintCashFluxActivationCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).MintCashFluxActivationCode(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ListCashFluxPendingDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ListCashFluxPendingDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ListCashFluxPendingDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ListCashFluxPendingDevices(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ApproveCashFluxPairing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CashFluxApprovePairingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ApproveCashFluxPairing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ApproveCashFluxPairing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ApproveCashFluxPairing(ctx, req.(*CashFluxApprovePairingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_RejectCashFluxPairing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CashFluxRejectPairingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).RejectCashFluxPairing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_RejectCashFluxPairing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).RejectCashFluxPairing(ctx, req.(*CashFluxRejectPairingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ListCashFluxUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CashFluxListUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ListCashFluxUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ListCashFluxUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ListCashFluxUsers(ctx, req.(*CashFluxListUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetCashFluxStorageStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetCashFluxStorageStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetCashFluxStorageStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetCashFluxStorageStats(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_DeleteCashFluxUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CashFluxDeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).DeleteCashFluxUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_DeleteCashFluxUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).DeleteCashFluxUser(ctx, req.(*CashFluxDeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminService_ServiceDesc is the grpc.ServiceDesc for AdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "site.v1.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _AdminService_Login_Handler,
		},
		{
			MethodName: "AuthState",
			Handler:    _AdminService_AuthState_Handler,
		},
		{
			MethodName: "Setup",
			Handler:    _AdminService_Setup_Handler,
		},
		{
			MethodName: "ResetPassword",
			Handler:    _AdminService_ResetPassword_Handler,
		},
		{
			MethodName: "SearchAnime",
			Handler:    _AdminService_SearchAnime_Handler,
		},
		{
			MethodName: "ListTracked",
			Handler:    _AdminService_ListTracked_Handler,
		},
		{
			MethodName: "TrackAnime",
			Handler:    _AdminService_TrackAnime_Handler,
		},
		{
			MethodName: "UntrackAnime",
			Handler:    _AdminService_UntrackAnime_Handler,
		},
		{
			MethodName: "RunReleaseCheck",
			Handler:    _AdminService_RunReleaseCheck_Handler,
		},
		{
			MethodName: "GetResume",
			Handler:    _AdminService_GetResume_Handler,
		},
		{
			MethodName: "ApplyResume",
			Handler:    _AdminService_ApplyResume_Handler,
		},
		{
			MethodName: "TailorResume",
			Handler:    _AdminService_TailorResume_Handler,
		},
		{
			MethodName: "GetSettings",
			Handler:    _AdminService_GetSettings_Handler,
		},
		{
			MethodName: "SaveSettings",
			Handler:    _AdminService_SaveSettings_Handler,
		},
		{
			MethodName: "ListModels",
			Handler:    _AdminService_ListModels_Handler,
		},
		{
			MethodName: "GetLastTailoring",
			Handler:    _AdminService_GetLastTailoring_Handler,
		},
		{
			MethodName: "GetBaseResume",
			Handler:    _AdminService_GetBaseResume_Handler,
		},
		{
			MethodName: "ListTailorings",
			Handler:    _AdminService_ListTailorings_Handler,
		},
		{
			MethodName: "GetTailoring",
			Handler:    _AdminService_GetTailoring_Handler,
		},
		{
			MethodName: "DeleteTailoring",
			Handler:    _AdminService_DeleteTailoring_Handler,
		},
		{
			MethodName: "GetPrompt",
			Handler:    _AdminService_GetPrompt_Handler,
		},
		{
			MethodName: "SavePrompt",
			Handler:    _AdminService_SavePrompt_Handler,
		},
		{
			MethodName: "DryRunPrompt",
			Handler:    _AdminService_DryRunPrompt_Handler,
		},
		{
			MethodName: "GetSlackConfig",
			Handler:    _AdminService_GetSlackConfig_Handler,
		},
		{
			MethodName: "SaveSlackConfig",
			Handler:    _AdminService_SaveSlackConfig_Handler,
		},
		{
			MethodName: "PostToSlackNow",
			Handler:    _AdminService_PostToSlackNow_Handler,
		},
		{
			MethodName: "MintCashFluxActivationCode",
			Handler:    _AdminService_MintCashFluxActivationCode_Handler,
		},
		{
			MethodName: "ListCashFluxPendingDevices",
			Handler:    _AdminService_ListCashFluxPendingDevices_Handler,
		},
		{
			MethodName: "ApproveCashFluxPairing",
			Handler:    _AdminService_ApproveCashFluxPairing_Handler,
		},
		{
			MethodName: "RejectCashFluxPairing",
			Handler:    _AdminService_RejectCashFluxPairing_Handler,
		},
		{
			MethodName: "ListCashFluxUsers",
			Handler:    _AdminService_ListCashFluxUsers_Handler,
		},
		{
			MethodName: "GetCashFluxStorageStats",
			Handler:    _AdminService_GetCashFluxStorageStats_Handler,
		},
		{
			MethodName: "DeleteCashFluxUser",
			Handler:    _AdminService_DeleteCashFluxUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin.proto",
}
