// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: site.proto

package sitepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PingRequest is empty; the round trip is the measurement.
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_site_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_site_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_site_proto_rawDescGZIP(), []int{0}
}

// PingResponse carries the server's own clock so a caller can tell a slow network from a slow
// server, rather than guessing from one number.
type PingResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ServerUnixMillis int64                  `protobuf:"varint,1,opt,name=server_unix_millis,json=serverUnixMillis,proto3" json:"server_unix_millis,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_site_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_site_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_site_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetServerUnixMillis() int64 {
	if x != nil {
		return x.ServerUnixMillis
	}
	return 0
}

// StatsRequest is empty — the stats are not parameterised.
type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_site_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_site_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_site_proto_rawDescGZIP(), []int{2}
}

// Stats are the live server facts `stats` prints.
type Stats struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Version is the build identifier (git SHA when built by the deploy script).
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// GoVersion is the toolchain that built the running binary.
	GoVersion string `protobuf:"bytes,2,opt,name=go_version,json=goVersion,proto3" json:"go_version,omitempty"`
	// UptimeSeconds is how long this process has been serving.
	UptimeSeconds int64 `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	// StartedUnixMillis is when the process began serving.
	StartedUnixMillis int64 `protobuf:"varint,4,opt,name=started_unix_millis,json=startedUnixMillis,proto3" json:"started_unix_millis,omitempty"`
	// RequestsServed counts HTTP requests handled since start.
	RequestsServed int64 `protobuf:"varint,5,opt,name=requests_served,json=requestsServed,proto3" json:"requests_served,omitempty"`
	// TerminalCommands counts commands run in the terminal since start.
	TerminalCommands int64 `protobuf:"varint,6,opt,name=terminal_commands,json=terminalCommands,proto3" json:"terminal_commands,omitempty"`
	// Goroutines is the live goroutine count — a small, honest window into the running process.
	Goroutines int32 `protobuf:"varint,7,opt,name=goroutines,proto3" json:"goroutines,omitempty"`
	// HeapBytes is the current heap in use.
	HeapBytes     int64 `protobuf:"varint,8,opt,name=heap_bytes,json=heapBytes,proto3" json:"heap_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stats) Reset() {
	*x = Stats{}
	mi := &file_site_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stats) ProtoMessage() {}

func (x *Stats) ProtoReflect() protoreflect.Message {
	mi := &file_site_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stats.ProtoReflect.Descriptor instead.
func (*Stats) Descriptor() ([]byte, []int) {
	return file_site_proto_rawDescGZIP(), []int{3}
}

func (x *Stats) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Stats) GetGoVersion() string {
	if x != nil {
		return x.GoVersion
	}
	return ""
}

func (x *Stats) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *Stats) GetStartedUnixMillis() int64 {
	if x != nil {
		return x.StartedUnixMillis
	}
	return 0
}

func (x *Stats) GetRequestsServed() int64 {
	if x != nil {
		return x.RequestsServed
	}
	return 0
}

func (x *Stats) GetTerminalCommands() int64 {
	if x != nil {
		return x.TerminalCommands
	}
	return 0
}

func (x *Stats) GetGoroutines() int32 {
	if x != nil {
		return x.Goroutines
	}
	return 0
}

func (x *Stats) GetHeapBytes() int64 {
	if x != nil {
		return x.HeapBytes
	}
	return 0
}

// CommandEvent reports that a terminal command ran.
//
// PRIVACY, by construction rather than by policy: the only field is a command NAME, and the
// server discards anything not on its known-command allowlist. No arguments, no free text (so a
// visitor's typing can never be recorded even by accident), no IP, no session or visitor id, no
// user agent, no timestamp finer than the day it is aggregated into. There is deliberately no
// field here that could identify a person, because the safest way not to store something is to
// have nowhere to put it.
type CommandEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandEvent) Reset() {
	*x = CommandEvent{}
	mi := &file_site_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandEvent) ProtoMessage() {}

func (x *CommandEvent) ProtoReflect() protoreflect.Message {
	mi := &file_site_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandEvent.ProtoReflect.Descriptor instead.
func (*CommandEvent) Descriptor() ([]byte, []int) {
	return file_site_proto_rawDescGZIP(), []int{4}
}

func (x *CommandEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Ack is a generic write acknowledgement.
type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_site_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_site_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_site_proto_rawDescGZIP(), []int{5}
}

func (x *Ack) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Ack) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// LocaleRequest selects the language for localized content (falls back to English).
type LocaleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locale        string                 `protobuf:"bytes,1,opt,name=locale,proto3" json:"locale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocaleRequest) Reset() {
	*x = LocaleRequest{}
	mi := &file_site_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocaleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocaleRequest) ProtoMessage() {}

func (x *LocaleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_site_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocaleRequest.ProtoReflect.Descriptor instead.
func (*LocaleRequest) Descriptor() ([]byte, []int) {
	return file_site_proto_rawDescGZIP(), []int{6}
}

func (x *LocaleRequest) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

// ProjectRequest identifies one project by id.
type ProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Locale        string                 `protobuf:"bytes,2,opt,name=locale,proto3" json:"locale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectRequest) Reset() {
	*x = ProjectRequest{}
	mi := &file_site_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectRequest) ProtoMessage() {}

func (x *ProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_site_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectRequest.ProtoReflect.Descriptor instead.
func (*ProjectRequest) Descriptor() ([]byte, []int) {
	return file_site_proto_rawDescGZIP(), []int{7}
}

func (x *ProjectRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProjectRequest) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

// About is the identity/thesis copy shown in the hero and `about`.
type About struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Headline      string                 `protobuf:"bytes,1,opt,name=headline,proto3" json:"headline,omitempty"`
	Body          string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *About) Reset() {
	*x = About{}
	mi := &file_site_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *About) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*About) ProtoMessage() {}

func (x *About) ProtoReflect() protoreflect.Message {
	mi := &file_site_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use About.ProtoReflect.Descriptor instead.
func (*About) Descriptor() ([]byte, []int) {
	return file_site_proto_rawDescGZIP(), []int{8}
}

func (x *About) GetHeadline() string {
	if x != nil {
		return x.Headline
	}
	return ""
}

func (x *About) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

// Project is one portfolio entry.
type Project struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Glyph         string                 `protobuf:"bytes,4,opt,name=glyph,proto3" json:"glyph,omitempty"`
	Blurb         string                 `protobuf:"bytes,5,opt,name=blurb,proto3" json:"blurb,omitempty"`
	Long          string                 `protobuf:"bytes,6,opt,name=long,proto3" json:"long,omitempty"`
	Repo          string                 `protobuf:"bytes,7,opt,name=repo,proto3" json:"repo,omitempty"`
	Demo          string                 `protobuf:"bytes,8,opt,name=demo,proto3" json:"demo,omitempty"`
	Tags          []string               `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_site_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_site_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_site_proto_rawDescGZIP(), []int{9}
}

func (x *Project) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Project) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Project) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Project) GetGlyph() string {
	if x != nil {
		return x.Glyph
	}
	return ""
}

func (x *Project) GetBlurb() string {
	if x != nil {
		return x.Blurb
	}
	return ""
}

func (x *Project) GetLong() string {
	if x != nil {
		return x.Long
	}
	return ""
}

func (x *Project) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *Project) GetDemo() string {
	if x != nil {
		return x.Demo
	}
	return ""
}

func (x *Project) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// ProjectList is the featured set, in display order.
type ProjectList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Projects      []*Project             `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectList) Reset() {
	*x = ProjectList{}
	mi := &file_site_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectList) ProtoMessage() {}

func (x *ProjectList) ProtoReflect() protoreflect.Message {
	mi := &file_site_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectList.ProtoReflect.Descriptor instead.
func (*ProjectList) Descriptor() ([]byte, []int) {
	return file_site_proto_rawDescGZIP(), []int{10}
}

func (x *ProjectList) GetProjects() []*Project {
	if x != nil {
		return x.Projects
	}
	return nil
}

// ContactMessage is a visitor's inbound message.
type ContactMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactMessage) Reset() {
	*x = ContactMessage{}
	mi := &file_site_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactMessage) ProtoMessage() {}

func (x *ContactMessage) ProtoReflect() protoreflect.Message {
	mi := &file_site_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactMessage.ProtoReflect.Descriptor instead.
func (*ContactMessage) Descriptor() ([]byte, []int) {
	return file_site_proto_rawDescGZIP(), []int{11}
}

func (x *ContactMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContactMessage) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ContactMessage) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

var File_site_proto protoreflect.FileDescriptor

const file_site_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"site.proto\x12\asite.v1\"\r\n" +
	"\vPingRequest\"<\n" +
	"\fPingResponse\x12,\n" +
	"\x12server_unix_millis\x18\x01 \x01(\x03R\x10serverUnixMillis\"\x0e\n" +
	"\fStatsRequest\"\xac\x02\n" +
	"\x05Stats\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"go_version\x18\x02 \x01(\tR\tgoVersion\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x03R\ruptimeSeconds\x12.\n" +
	"\x13started_unix_millis\x18\x04 \x01(\x03R\x11startedUnixMillis\x12'\n" +
	"\x0frequests_served\x18\x05 \x01(\x03R\x0erequestsServed\x12+\n" +
	"\x11terminal_commands\x18\x06 \x01(\x03R\x10terminalCommands\x12\x1e\n" +
	"\n" +
	"goroutines\x18\a \x01(\x05R\n" +
	"goroutines\x12\x1d\n" +
	"\n" +
	"heap_bytes\x18\b \x01(\x03R\theapBytes\"\"\n" +
	"\fCommandEvent\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"/\n" +
	"\x03Ack\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"'\n" +
	"\rLocaleRequest\x12\x16\n" +
	"\x06locale\x18\x01 \x01(\tR\x06locale\"8\n" +
	"\x0eProjectRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06locale\x18\x02 \x01(\tR\x06locale\"7\n" +
	"\x05About\x12\x1a\n" +
	"\bheadline\x18\x01 \x01(\tR\bheadline\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\"\xc1\x01\n" +
	"\aProject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x14\n" +
	"\x05glyph\x18\x04 \x01(\tR\x05glyph\x12\x14\n" +
	"\x05blurb\x18\x05 \x01(\tR\x05blurb\x12\x12\n" +
	"\x04long\x18\x06 \x01(\tR\x04long\x12\x12\n" +
	"\x04repo\x18\a \x01(\tR\x04repo\x12\x12\n" +
	"\x04demo\x18\b \x01(\tR\x04demo\x12\x12\n" +
	"\x04tags\x18\t \x03(\tR\x04tags\";\n" +
	"\vProjectList\x12,\n" +
	"\bprojects\x18\x01 \x03(\v2\x10.site.v1.ProjectR\bprojects\"N\n" +
	"\x0eContactMessage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body2\xbb\x01\n" +
	"\x0eContentService\x122\n" +
	"\bGetAbout\x12\x16.site.v1.LocaleRequest\x1a\x0e.site.v1.About\x12<\n" +
	"\fListProjects\x12\x16.site.v1.LocaleRequest\x1a\x14.site.v1.ProjectList\x127\n" +
	"\n" +
	"GetProject\x12\x17.site.v1.ProjectRequest\x1a\x10.site.v1.Project2F\n" +
	"\x0eContactService\x124\n" +
	"\vSendMessage\x12\x17.site.v1.ContactMessage\x1a\f.site.v1.Ack2\xad\x01\n" +
	"\rSystemService\x123\n" +
	"\x04Ping\x12\x14.site.v1.PingRequest\x1a\x15.site.v1.PingResponse\x121\n" +
	"\bGetStats\x12\x15.site.v1.StatsRequest\x1a\x0e.site.v1.Stats\x124\n" +
	"\rRecordCommand\x12\x15.site.v1.CommandEvent\x1a\f.site.v1.AckB;Z9github.com/monstercameron/earlcameron/proto/sitepb;sitepbb\x06proto3"

var (
	file_site_proto_rawDescOnce sync.Once
	file_site_proto_rawDescData []byte
)

func file_site_proto_rawDescGZIP() []byte {
	file_site_proto_rawDescOnce.Do(func() {
		file_site_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_site_proto_rawDesc), len(file_site_proto_rawDesc)))
	})
	return file_site_proto_rawDescData
}

var file_site_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_site_proto_goTypes = []any{
	(*PingRequest)(nil),    // 0: site.v1.PingRequest
	(*PingResponse)(nil),   // 1: site.v1.PingResponse
	(*StatsRequest)(nil),   // 2: site.v1.StatsRequest
	(*Stats)(nil),          // 3: site.v1.Stats
	(*CommandEvent)(nil),   // 4: site.v1.CommandEvent
	(*Ack)(nil),            // 5: site.v1.Ack
	(*LocaleRequest)(nil),  // 6: site.v1.LocaleRequest
	(*ProjectRequest)(nil), // 7: site.v1.ProjectRequest
	(*About)(nil),          // 8: site.v1.About
	(*Project)(nil),        // 9: site.v1.Project
	(*ProjectList)(nil),    // 10: site.v1.ProjectList
	(*ContactMessage)(nil), // 11: site.v1.ContactMessage
}
var file_site_proto_depIdxs = []int32{
	9,  // 0: site.v1.ProjectList.projects:type_name -> site.v1.Project
	6,  // 1: site.v1.ContentService.GetAbout:input_type -> site.v1.LocaleRequest
	6,  // 2: site.v1.ContentService.ListProjects:input_type -> site.v1.LocaleRequest
	7,  // 3: site.v1.ContentService.GetProject:input_type -> site.v1.ProjectRequest
	11, // 4: site.v1.ContactService.SendMessage:input_type -> site.v1.ContactMessage
	0,  // 5: site.v1.SystemService.Ping:input_type -> site.v1.PingRequest
	2,  // 6: site.v1.SystemService.GetStats:input_type -> site.v1.StatsRequest
	4,  // 7: site.v1.SystemService.RecordCommand:input_type -> site.v1.CommandEvent
	8,  // 8: site.v1.ContentService.GetAbout:output_type -> site.v1.About
	10, // 9: site.v1.ContentService.ListProjects:output_type -> site.v1.ProjectList
	9,  // 10: site.v1.ContentService.GetProject:output_type -> site.v1.Project
	5,  // 11: site.v1.ContactService.SendMessage:output_type -> site.v1.Ack
	1,  // 12: site.v1.SystemService.Ping:output_type -> site.v1.PingResponse
	3,  // 13: site.v1.SystemService.GetStats:output_type -> site.v1.Stats
	5,  // 14: site.v1.SystemService.RecordCommand:output_type -> site.v1.Ack
	8,  // [8:15] is the sub-list for method output_type
	1,  // [1:8] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_site_proto_init() }
func file_site_proto_init() {
	if File_site_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_site_proto_rawDesc), len(file_site_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_site_proto_goTypes,
		DependencyIndexes: file_site_proto_depIdxs,
		MessageInfos:      file_site_proto_msgTypes,
	}.Build()
	File_site_proto = out.File
	file_site_proto_goTypes = nil
	file_site_proto_depIdxs = nil
}
