// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: site.proto

package sitepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Ack is a generic write acknowledgement.
type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_site_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_site_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_site_proto_rawDescGZIP(), []int{0}
}

func (x *Ack) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Ack) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// LocaleRequest selects the language for localized content (falls back to English).
type LocaleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locale        string                 `protobuf:"bytes,1,opt,name=locale,proto3" json:"locale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocaleRequest) Reset() {
	*x = LocaleRequest{}
	mi := &file_site_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocaleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocaleRequest) ProtoMessage() {}

func (x *LocaleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_site_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocaleRequest.ProtoReflect.Descriptor instead.
func (*LocaleRequest) Descriptor() ([]byte, []int) {
	return file_site_proto_rawDescGZIP(), []int{1}
}

func (x *LocaleRequest) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

// ProjectRequest identifies one project by id.
type ProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Locale        string                 `protobuf:"bytes,2,opt,name=locale,proto3" json:"locale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectRequest) Reset() {
	*x = ProjectRequest{}
	mi := &file_site_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectRequest) ProtoMessage() {}

func (x *ProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_site_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectRequest.ProtoReflect.Descriptor instead.
func (*ProjectRequest) Descriptor() ([]byte, []int) {
	return file_site_proto_rawDescGZIP(), []int{2}
}

func (x *ProjectRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProjectRequest) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

// About is the identity/thesis copy shown in the hero and `about`.
type About struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Headline      string                 `protobuf:"bytes,1,opt,name=headline,proto3" json:"headline,omitempty"`
	Body          string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *About) Reset() {
	*x = About{}
	mi := &file_site_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *About) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*About) ProtoMessage() {}

func (x *About) ProtoReflect() protoreflect.Message {
	mi := &file_site_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use About.ProtoReflect.Descriptor instead.
func (*About) Descriptor() ([]byte, []int) {
	return file_site_proto_rawDescGZIP(), []int{3}
}

func (x *About) GetHeadline() string {
	if x != nil {
		return x.Headline
	}
	return ""
}

func (x *About) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

// Project is one portfolio entry.
type Project struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Glyph         string                 `protobuf:"bytes,4,opt,name=glyph,proto3" json:"glyph,omitempty"`
	Blurb         string                 `protobuf:"bytes,5,opt,name=blurb,proto3" json:"blurb,omitempty"`
	Long          string                 `protobuf:"bytes,6,opt,name=long,proto3" json:"long,omitempty"`
	Repo          string                 `protobuf:"bytes,7,opt,name=repo,proto3" json:"repo,omitempty"`
	Demo          string                 `protobuf:"bytes,8,opt,name=demo,proto3" json:"demo,omitempty"`
	Tags          []string               `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_site_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_site_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_site_proto_rawDescGZIP(), []int{4}
}

func (x *Project) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Project) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Project) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Project) GetGlyph() string {
	if x != nil {
		return x.Glyph
	}
	return ""
}

func (x *Project) GetBlurb() string {
	if x != nil {
		return x.Blurb
	}
	return ""
}

func (x *Project) GetLong() string {
	if x != nil {
		return x.Long
	}
	return ""
}

func (x *Project) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *Project) GetDemo() string {
	if x != nil {
		return x.Demo
	}
	return ""
}

func (x *Project) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// ProjectList is the featured set, in display order.
type ProjectList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Projects      []*Project             `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectList) Reset() {
	*x = ProjectList{}
	mi := &file_site_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectList) ProtoMessage() {}

func (x *ProjectList) ProtoReflect() protoreflect.Message {
	mi := &file_site_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectList.ProtoReflect.Descriptor instead.
func (*ProjectList) Descriptor() ([]byte, []int) {
	return file_site_proto_rawDescGZIP(), []int{5}
}

func (x *ProjectList) GetProjects() []*Project {
	if x != nil {
		return x.Projects
	}
	return nil
}

// ContactMessage is a visitor's inbound message.
type ContactMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactMessage) Reset() {
	*x = ContactMessage{}
	mi := &file_site_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactMessage) ProtoMessage() {}

func (x *ContactMessage) ProtoReflect() protoreflect.Message {
	mi := &file_site_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactMessage.ProtoReflect.Descriptor instead.
func (*ContactMessage) Descriptor() ([]byte, []int) {
	return file_site_proto_rawDescGZIP(), []int{6}
}

func (x *ContactMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContactMessage) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ContactMessage) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

var File_site_proto protoreflect.FileDescriptor

const file_site_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"site.proto\x12\asite.v1\"/\n" +
	"\x03Ack\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"'\n" +
	"\rLocaleRequest\x12\x16\n" +
	"\x06locale\x18\x01 \x01(\tR\x06locale\"8\n" +
	"\x0eProjectRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06locale\x18\x02 \x01(\tR\x06locale\"7\n" +
	"\x05About\x12\x1a\n" +
	"\bheadline\x18\x01 \x01(\tR\bheadline\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\"\xc1\x01\n" +
	"\aProject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x14\n" +
	"\x05glyph\x18\x04 \x01(\tR\x05glyph\x12\x14\n" +
	"\x05blurb\x18\x05 \x01(\tR\x05blurb\x12\x12\n" +
	"\x04long\x18\x06 \x01(\tR\x04long\x12\x12\n" +
	"\x04repo\x18\a \x01(\tR\x04repo\x12\x12\n" +
	"\x04demo\x18\b \x01(\tR\x04demo\x12\x12\n" +
	"\x04tags\x18\t \x03(\tR\x04tags\";\n" +
	"\vProjectList\x12,\n" +
	"\bprojects\x18\x01 \x03(\v2\x10.site.v1.ProjectR\bprojects\"N\n" +
	"\x0eContactMessage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body2\xbb\x01\n" +
	"\x0eContentService\x122\n" +
	"\bGetAbout\x12\x16.site.v1.LocaleRequest\x1a\x0e.site.v1.About\x12<\n" +
	"\fListProjects\x12\x16.site.v1.LocaleRequest\x1a\x14.site.v1.ProjectList\x127\n" +
	"\n" +
	"GetProject\x12\x17.site.v1.ProjectRequest\x1a\x10.site.v1.Project2F\n" +
	"\x0eContactService\x124\n" +
	"\vSendMessage\x12\x17.site.v1.ContactMessage\x1a\f.site.v1.AckB;Z9github.com/monstercameron/earlcameron/proto/sitepb;sitepbb\x06proto3"

var (
	file_site_proto_rawDescOnce sync.Once
	file_site_proto_rawDescData []byte
)

func file_site_proto_rawDescGZIP() []byte {
	file_site_proto_rawDescOnce.Do(func() {
		file_site_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_site_proto_rawDesc), len(file_site_proto_rawDesc)))
	})
	return file_site_proto_rawDescData
}

var file_site_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_site_proto_goTypes = []any{
	(*Ack)(nil),            // 0: site.v1.Ack
	(*LocaleRequest)(nil),  // 1: site.v1.LocaleRequest
	(*ProjectRequest)(nil), // 2: site.v1.ProjectRequest
	(*About)(nil),          // 3: site.v1.About
	(*Project)(nil),        // 4: site.v1.Project
	(*ProjectList)(nil),    // 5: site.v1.ProjectList
	(*ContactMessage)(nil), // 6: site.v1.ContactMessage
}
var file_site_proto_depIdxs = []int32{
	4, // 0: site.v1.ProjectList.projects:type_name -> site.v1.Project
	1, // 1: site.v1.ContentService.GetAbout:input_type -> site.v1.LocaleRequest
	1, // 2: site.v1.ContentService.ListProjects:input_type -> site.v1.LocaleRequest
	2, // 3: site.v1.ContentService.GetProject:input_type -> site.v1.ProjectRequest
	6, // 4: site.v1.ContactService.SendMessage:input_type -> site.v1.ContactMessage
	3, // 5: site.v1.ContentService.GetAbout:output_type -> site.v1.About
	5, // 6: site.v1.ContentService.ListProjects:output_type -> site.v1.ProjectList
	4, // 7: site.v1.ContentService.GetProject:output_type -> site.v1.Project
	0, // 8: site.v1.ContactService.SendMessage:output_type -> site.v1.Ack
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_site_proto_init() }
func file_site_proto_init() {
	if File_site_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_site_proto_rawDesc), len(file_site_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_site_proto_goTypes,
		DependencyIndexes: file_site_proto_depIdxs,
		MessageInfos:      file_site_proto_msgTypes,
	}.Build()
	File_site_proto = out.File
	file_site_proto_goTypes = nil
	file_site_proto_depIdxs = nil
}
